// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_fft (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        f_first_address0,
        f_first_ce0,
        f_first_we0,
        f_first_d0,
        f_first_q0,
        f_first_address1,
        f_first_ce1,
        f_first_we1,
        f_first_d1,
        f_first_q1,
        tmp_s,
        f_second_address0,
        f_second_ce0,
        f_second_we0,
        f_second_d0,
        f_second_q0,
        f_second_address1,
        f_second_ce1,
        f_second_we1,
        f_second_d1,
        f_second_q1,
        tmp_1
);

parameter    ap_ST_st1_fsm_0 = 31'b1;
parameter    ap_ST_st2_fsm_1 = 31'b10;
parameter    ap_ST_st3_fsm_2 = 31'b100;
parameter    ap_ST_st4_fsm_3 = 31'b1000;
parameter    ap_ST_st5_fsm_4 = 31'b10000;
parameter    ap_ST_st6_fsm_5 = 31'b100000;
parameter    ap_ST_st7_fsm_6 = 31'b1000000;
parameter    ap_ST_st8_fsm_7 = 31'b10000000;
parameter    ap_ST_st9_fsm_8 = 31'b100000000;
parameter    ap_ST_st10_fsm_9 = 31'b1000000000;
parameter    ap_ST_st11_fsm_10 = 31'b10000000000;
parameter    ap_ST_st12_fsm_11 = 31'b100000000000;
parameter    ap_ST_st13_fsm_12 = 31'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 31'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 31'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 31'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 31'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 31'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 31'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 31'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 31'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 31'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 31'b10000000000000000000000;
parameter    ap_ST_st24_fsm_23 = 31'b100000000000000000000000;
parameter    ap_ST_st25_fsm_24 = 31'b1000000000000000000000000;
parameter    ap_ST_st26_fsm_25 = 31'b10000000000000000000000000;
parameter    ap_ST_st27_fsm_26 = 31'b100000000000000000000000000;
parameter    ap_ST_st28_fsm_27 = 31'b1000000000000000000000000000;
parameter    ap_ST_st29_fsm_28 = 31'b10000000000000000000000000000;
parameter    ap_ST_st30_fsm_29 = 31'b100000000000000000000000000000;
parameter    ap_ST_st31_fsm_30 = 31'b1000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_80 = 32'b10000000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_3F7FEC44 = 32'b111111011111111110110001000100;
parameter    ap_const_lv32_3CC90A77 = 32'b111100110010010000101001110111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv32_FF = 32'b11111111;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] f_first_address0;
output   f_first_ce0;
output   f_first_we0;
output  [31:0] f_first_d0;
input  [31:0] f_first_q0;
output  [13:0] f_first_address1;
output   f_first_ce1;
output   f_first_we1;
output  [31:0] f_first_d1;
input  [31:0] f_first_q1;
input  [5:0] tmp_s;
output  [13:0] f_second_address0;
output   f_second_ce0;
output   f_second_we0;
output  [31:0] f_second_d0;
input  [31:0] f_second_q0;
output  [13:0] f_second_address1;
output   f_second_ce1;
output   f_second_we1;
output  [31:0] f_second_d1;
input  [31:0] f_second_q1;
input  [5:0] tmp_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] f_first_address0;
reg f_first_ce0;
reg f_first_we0;
reg[31:0] f_first_d0;
reg[13:0] f_first_address1;
reg f_first_ce1;
reg f_first_we1;
reg[13:0] f_second_address0;
reg f_second_ce0;
reg f_second_we0;
reg[31:0] f_second_d0;
reg[13:0] f_second_address1;
reg f_second_ce1;
reg f_second_we1;

(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_48;
reg   [31:0] reg_258;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_87;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_94;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_102;
reg    ap_sig_cseq_ST_st25_fsm_24;
reg    ap_sig_109;
reg   [31:0] reg_267;
wire   [31:0] grp_fu_226_p2;
reg   [31:0] reg_276;
reg    ap_sig_cseq_ST_st30_fsm_29;
reg    ap_sig_120;
wire   [31:0] grp_fu_230_p2;
reg   [31:0] reg_282;
wire   [14:0] tmp_67_cast_fu_296_p1;
reg   [14:0] tmp_67_cast_reg_597;
wire   [14:0] tmp_69_cast_fu_308_p1;
reg   [14:0] tmp_69_cast_reg_604;
wire   [0:0] tmp_fu_322_p2;
reg   [0:0] tmp_reg_614;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_143;
wire   [0:0] exitcond1_fu_316_p2;
reg   [13:0] f_first_addr_reg_618;
reg   [13:0] f_second_addr_reg_623;
reg   [13:0] f_first_addr_1_reg_628;
reg   [13:0] f_second_addr_1_reg_633;
wire   [31:0] j_8_fu_382_p2;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_168;
wire   [0:0] tmp_47_fu_376_p2;
wire   [31:0] k_5_fu_436_p3;
wire   [31:0] j_7_fu_444_p2;
wire   [7:0] tmp_48_fu_450_p2;
wire   [31:0] la_cast_fu_472_p1;
reg   [31:0] la_cast_reg_664;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_188;
wire   [0:0] exitcond_fu_460_p2;
wire   [7:0] p_lshr_f1_cast_fu_476_p4;
reg   [7:0] p_lshr_f1_cast_reg_669;
wire   [7:0] tmp_14_fu_486_p2;
reg   [7:0] tmp_14_reg_674;
wire   [31:0] n_cast_fu_503_p1;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_204;
wire   [0:0] exitcond11_fu_492_p2;
wire   [3:0] m_1_fu_507_p2;
reg   [13:0] f_first_addr_2_reg_695;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_220;
wire   [0:0] tmp_51_fu_513_p2;
reg   [13:0] f_second_addr_2_reg_700;
reg   [13:0] f_first_addr_3_reg_705;
reg   [13:0] f_second_addr_3_reg_711;
wire   [31:0] n_1_fu_576_p2;
reg   [31:0] n_1_reg_717;
wire   [7:0] l_1_fu_581_p2;
wire   [31:0] grp_fu_234_p2;
reg   [31:0] tmp_i_reg_727;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_244;
wire   [31:0] grp_fu_240_p2;
reg   [31:0] tmp_i_30_reg_732;
wire   [31:0] grp_fu_246_p2;
reg   [31:0] tmp_123_i_reg_737;
wire   [31:0] grp_fu_252_p2;
reg   [31:0] tmp_124_i_reg_742;
reg   [31:0] c_first_write_assign_reg_747;
reg    ap_sig_cseq_ST_st22_fsm_21;
reg    ap_sig_258;
reg   [31:0] c_second_write_assign_reg_752;
reg   [31:0] j_reg_148;
reg   [7:0] i_1_reg_160;
reg   [31:0] k_reg_172;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_274;
reg   [31:0] j_1_reg_183;
reg   [3:0] m_reg_193;
reg   [7:0] l_reg_205;
reg   [31:0] n1_reg_217;
reg    ap_sig_cseq_ST_st31_fsm_30;
reg    ap_sig_292;
wire   [63:0] tmp_70_cast_fu_337_p1;
wire   [63:0] tmp_71_cast_fu_347_p1;
wire   [63:0] tmp_45_fu_359_p1;
wire   [63:0] tmp_46_fu_371_p1;
wire  signed [63:0] tmp_78_cast_fu_537_p1;
wire  signed [63:0] tmp_79_cast_fu_547_p1;
wire  signed [63:0] tmp_80_cast_fu_561_p1;
wire  signed [63:0] tmp_81_cast_fu_571_p1;
reg    ap_sig_cseq_ST_st23_fsm_22;
reg    ap_sig_308;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_323;
reg    ap_sig_cseq_ST_st24_fsm_23;
reg    ap_sig_331;
reg   [31:0] grp_fu_226_p0;
reg   [31:0] grp_fu_226_p1;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_344;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_351;
reg    ap_sig_cseq_ST_st26_fsm_25;
reg    ap_sig_358;
reg   [31:0] grp_fu_230_p0;
reg   [31:0] grp_fu_230_p1;
wire   [13:0] tmp_4_fu_288_p3;
wire   [13:0] tmp_5_fu_300_p3;
wire   [31:0] i_1_cast2_fu_312_p1;
wire   [14:0] tmp_6_fu_328_p1;
wire   [14:0] tmp_43_fu_332_p2;
wire   [14:0] tmp_44_fu_342_p2;
wire   [13:0] tmp_7_fu_352_p3;
wire   [13:0] tmp_8_fu_364_p3;
wire   [31:0] p_neg_fu_396_p2;
wire   [30:0] p_lshr_fu_402_p4;
wire   [31:0] tmp_49_fu_412_p1;
wire   [30:0] p_lshr_f_fu_422_p4;
wire   [0:0] tmp_9_fu_388_p3;
wire   [31:0] p_neg_t_fu_416_p2;
wire   [31:0] tmp_50_fu_432_p1;
wire   [8:0] m_cast1_fu_456_p1;
wire   [8:0] la_fu_466_p2;
wire   [7:0] n_fu_497_p2;
wire   [14:0] tmp_11_fu_523_p1;
wire   [14:0] tmp_10_fu_519_p1;
wire   [14:0] tmp_12_fu_526_p2;
wire   [14:0] tmp_52_fu_532_p2;
wire   [14:0] tmp_53_fu_542_p2;
wire   [14:0] tmp_13_fu_552_p1;
wire   [14:0] tmp_54_fu_556_p2;
wire   [14:0] tmp_55_fu_566_p2;
reg   [1:0] grp_fu_226_opcode;
reg   [1:0] grp_fu_230_opcode;
reg   [30:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'b1;
end

dut_faddfsub_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_faddfsub_32ns_32ns_32_5_full_dsp_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_226_p0),
    .din1(grp_fu_226_p1),
    .opcode(grp_fu_226_opcode),
    .ce(1'b1),
    .dout(grp_fu_226_p2)
);

dut_faddfsub_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_faddfsub_32ns_32ns_32_5_full_dsp_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_230_p0),
    .din1(grp_fu_230_p1),
    .opcode(grp_fu_230_opcode),
    .ce(1'b1),
    .dout(grp_fu_230_p2)
);

dut_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fmul_32ns_32ns_32_4_max_dsp_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f_first_q0),
    .din1(ap_const_lv32_3F7FEC44),
    .ce(1'b1),
    .dout(grp_fu_234_p2)
);

dut_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fmul_32ns_32ns_32_4_max_dsp_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f_second_q0),
    .din1(ap_const_lv32_3CC90A77),
    .ce(1'b1),
    .dout(grp_fu_240_p2)
);

dut_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fmul_32ns_32ns_32_4_max_dsp_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f_first_q0),
    .din1(ap_const_lv32_3CC90A77),
    .ce(1'b1),
    .dout(grp_fu_246_p2)
);

dut_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fmul_32ns_32ns_32_4_max_dsp_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f_second_q0),
    .din1(ap_const_lv32_3F7FEC44),
    .ce(1'b1),
    .dout(grp_fu_252_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == tmp_47_fu_376_p2))) begin
        i_1_reg_160 <= tmp_48_fu_450_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        i_1_reg_160 <= ap_const_lv8_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & (1'b0 == tmp_47_fu_376_p2))) begin
        j_1_reg_183 <= j_8_fu_382_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        j_1_reg_183 <= j_reg_148;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == tmp_47_fu_376_p2))) begin
        j_reg_148 <= j_7_fu_444_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        j_reg_148 <= ap_const_lv32_80;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & (1'b0 == tmp_47_fu_376_p2))) begin
        k_reg_172 <= k_5_fu_436_p3;
    end else if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        k_reg_172 <= ap_const_lv32_80;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b0 == tmp_51_fu_513_p2))) begin
        l_reg_205 <= l_1_fu_581_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & (1'b0 == exitcond_fu_460_p2))) begin
        l_reg_205 <= ap_const_lv8_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_316_p2 == 1'b0))) begin
        m_reg_193 <= ap_const_lv4_1;
    end else if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == exitcond11_fu_492_p2))) begin
        m_reg_193 <= m_1_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        n1_reg_217 <= n_1_reg_717;
    end else if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & (1'b0 == exitcond11_fu_492_p2))) begin
        n1_reg_217 <= n_cast_fu_503_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_16) | (1'b1 == ap_sig_cseq_ST_st25_fsm_24))) begin
        reg_258 <= f_first_q1;
    end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        reg_258 <= f_first_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_16) | (1'b1 == ap_sig_cseq_ST_st25_fsm_24))) begin
        reg_267 <= f_second_q1;
    end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        reg_267 <= f_second_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        c_first_write_assign_reg_747 <= grp_fu_226_p2;
        c_second_write_assign_reg_752 <= grp_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_316_p2 == 1'b0) & ~(tmp_fu_322_p2 == 1'b0))) begin
        f_first_addr_1_reg_628 <= tmp_45_fu_359_p1;
        f_first_addr_reg_618 <= tmp_70_cast_fu_337_p1;
        f_second_addr_1_reg_633 <= tmp_46_fu_371_p1;
        f_second_addr_reg_623 <= tmp_71_cast_fu_347_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & ~(1'b0 == tmp_51_fu_513_p2))) begin
        f_first_addr_2_reg_695 <= tmp_78_cast_fu_537_p1;
        f_first_addr_3_reg_705 <= tmp_80_cast_fu_561_p1;
        f_second_addr_2_reg_700 <= tmp_79_cast_fu_547_p1;
        f_second_addr_3_reg_711 <= tmp_81_cast_fu_571_p1;
        n_1_reg_717 <= n_1_fu_576_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & (1'b0 == exitcond_fu_460_p2))) begin
        la_cast_reg_664[8 : 0] <= la_cast_fu_472_p1[8 : 0];
        p_lshr_f1_cast_reg_669 <= {{la_fu_466_p2[ap_const_lv32_8 : ap_const_lv32_1]}};
        tmp_14_reg_674 <= tmp_14_fu_486_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_16) | (1'b1 == ap_sig_cseq_ST_st30_fsm_29))) begin
        reg_276 <= grp_fu_226_p2;
        reg_282 <= grp_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        tmp_123_i_reg_737 <= grp_fu_246_p2;
        tmp_124_i_reg_742 <= grp_fu_252_p2;
        tmp_i_30_reg_732 <= grp_fu_240_p2;
        tmp_i_reg_727 <= grp_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        tmp_67_cast_reg_597[13 : 8] <= tmp_67_cast_fu_296_p1[13 : 8];
        tmp_69_cast_reg_604[13 : 8] <= tmp_69_cast_fu_308_p1[13 : 8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_316_p2 == 1'b0))) begin
        tmp_reg_614 <= tmp_fu_322_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == exitcond_fu_460_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == exitcond_fu_460_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_244) begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_344) begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_323) begin
        ap_sig_cseq_ST_st16_fsm_15 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_102) begin
        ap_sig_cseq_ST_st17_fsm_16 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_351) begin
        ap_sig_cseq_ST_st18_fsm_17 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_48) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_258) begin
        ap_sig_cseq_ST_st22_fsm_21 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_21 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_308) begin
        ap_sig_cseq_ST_st23_fsm_22 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st23_fsm_22 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_331) begin
        ap_sig_cseq_ST_st24_fsm_23 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st24_fsm_23 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_109) begin
        ap_sig_cseq_ST_st25_fsm_24 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st25_fsm_24 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_358) begin
        ap_sig_cseq_ST_st26_fsm_25 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st26_fsm_25 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_143) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_120) begin
        ap_sig_cseq_ST_st30_fsm_29 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st30_fsm_29 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_292) begin
        ap_sig_cseq_ST_st31_fsm_30 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st31_fsm_30 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_87) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_274) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_168) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_188) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_204) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_220) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_94) begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        f_first_address0 = f_first_addr_3_reg_705;
    end else if ((1'b1 == ap_sig_cseq_ST_st23_fsm_22)) begin
        f_first_address0 = f_first_addr_2_reg_695;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        f_first_address0 = f_first_addr_reg_618;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        f_first_address0 = tmp_78_cast_fu_537_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        f_first_address0 = tmp_70_cast_fu_337_p1;
    end else begin
        f_first_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        f_first_address1 = f_first_addr_1_reg_628;
    end else if (((1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        f_first_address1 = f_first_addr_3_reg_705;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        f_first_address1 = tmp_45_fu_359_p1;
    end else begin
        f_first_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st31_fsm_30) | (1'b1 == ap_sig_cseq_ST_st23_fsm_22))) begin
        f_first_ce0 = 1'b1;
    end else begin
        f_first_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        f_first_ce1 = 1'b1;
    end else begin
        f_first_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        f_first_d0 = reg_276;
    end else if ((1'b1 == ap_sig_cseq_ST_st23_fsm_22)) begin
        f_first_d0 = c_first_write_assign_reg_747;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        f_first_d0 = f_first_q1;
    end else begin
        f_first_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st31_fsm_30) | (1'b1 == ap_sig_cseq_ST_st23_fsm_22))) begin
        f_first_we0 = 1'b1;
    end else begin
        f_first_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_614 == 1'b0))) begin
        f_first_we1 = 1'b1;
    end else begin
        f_first_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        f_second_address0 = f_second_addr_3_reg_711;
    end else if ((1'b1 == ap_sig_cseq_ST_st23_fsm_22)) begin
        f_second_address0 = f_second_addr_2_reg_700;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        f_second_address0 = f_second_addr_reg_623;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        f_second_address0 = tmp_79_cast_fu_547_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        f_second_address0 = tmp_71_cast_fu_347_p1;
    end else begin
        f_second_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        f_second_address1 = f_second_addr_1_reg_633;
    end else if (((1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        f_second_address1 = f_second_addr_3_reg_711;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        f_second_address1 = tmp_46_fu_371_p1;
    end else begin
        f_second_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st31_fsm_30) | (1'b1 == ap_sig_cseq_ST_st23_fsm_22))) begin
        f_second_ce0 = 1'b1;
    end else begin
        f_second_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        f_second_ce1 = 1'b1;
    end else begin
        f_second_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        f_second_d0 = reg_282;
    end else if ((1'b1 == ap_sig_cseq_ST_st23_fsm_22)) begin
        f_second_d0 = c_second_write_assign_reg_752;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        f_second_d0 = f_second_q1;
    end else begin
        f_second_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st31_fsm_30) | (1'b1 == ap_sig_cseq_ST_st23_fsm_22))) begin
        f_second_we0 = 1'b1;
    end else begin
        f_second_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_614 == 1'b0))) begin
        f_second_we1 = 1'b1;
    end else begin
        f_second_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) | (1'b1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        grp_fu_226_opcode = ap_const_lv2_1;
    end else if ((1'b1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        grp_fu_226_opcode = ap_const_lv2_0;
    end else begin
        grp_fu_226_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        grp_fu_226_p0 = reg_258;
    end else if ((1'b1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_226_p0 = tmp_i_reg_727;
    end else begin
        grp_fu_226_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        grp_fu_226_p1 = reg_276;
    end else if ((1'b1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_226_p1 = tmp_i_30_reg_732;
    end else begin
        grp_fu_226_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        grp_fu_230_opcode = ap_const_lv2_1;
    end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        grp_fu_230_opcode = ap_const_lv2_0;
    end else begin
        grp_fu_230_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        grp_fu_230_p0 = reg_267;
    end else if ((1'b1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_230_p0 = tmp_123_i_reg_737;
    end else begin
        grp_fu_230_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        grp_fu_230_p1 = reg_282;
    end else if ((1'b1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_230_p1 = tmp_124_i_reg_742;
    end else begin
        grp_fu_230_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (((exitcond1_fu_316_p2 == 1'b0) & (tmp_fu_322_p2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else if (((exitcond1_fu_316_p2 == 1'b0) & ~(tmp_fu_322_p2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            if (~(1'b0 == tmp_47_fu_376_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : begin
            if (~(1'b0 == exitcond_fu_460_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st7_fsm_6 : begin
            if (~(1'b0 == exitcond11_fu_492_p2)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st8_fsm_7 : begin
            if ((1'b0 == tmp_51_fu_513_p2)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : begin
            ap_NS_fsm = ap_ST_st21_fsm_20;
        end
        ap_ST_st21_fsm_20 : begin
            ap_NS_fsm = ap_ST_st22_fsm_21;
        end
        ap_ST_st22_fsm_21 : begin
            ap_NS_fsm = ap_ST_st23_fsm_22;
        end
        ap_ST_st23_fsm_22 : begin
            ap_NS_fsm = ap_ST_st24_fsm_23;
        end
        ap_ST_st24_fsm_23 : begin
            ap_NS_fsm = ap_ST_st25_fsm_24;
        end
        ap_ST_st25_fsm_24 : begin
            ap_NS_fsm = ap_ST_st26_fsm_25;
        end
        ap_ST_st26_fsm_25 : begin
            ap_NS_fsm = ap_ST_st27_fsm_26;
        end
        ap_ST_st27_fsm_26 : begin
            ap_NS_fsm = ap_ST_st28_fsm_27;
        end
        ap_ST_st28_fsm_27 : begin
            ap_NS_fsm = ap_ST_st29_fsm_28;
        end
        ap_ST_st29_fsm_28 : begin
            ap_NS_fsm = ap_ST_st30_fsm_29;
        end
        ap_ST_st30_fsm_29 : begin
            ap_NS_fsm = ap_ST_st31_fsm_30;
        end
        ap_ST_st31_fsm_30 : begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_102 = (1'b1 == ap_CS_fsm[ap_const_lv32_10]);
end

always @ (*) begin
    ap_sig_109 = (1'b1 == ap_CS_fsm[ap_const_lv32_18]);
end

always @ (*) begin
    ap_sig_120 = (1'b1 == ap_CS_fsm[ap_const_lv32_1D]);
end

always @ (*) begin
    ap_sig_143 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_168 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_188 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_204 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_220 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_244 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_258 = (1'b1 == ap_CS_fsm[ap_const_lv32_15]);
end

always @ (*) begin
    ap_sig_274 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_292 = (1'b1 == ap_CS_fsm[ap_const_lv32_1E]);
end

always @ (*) begin
    ap_sig_308 = (1'b1 == ap_CS_fsm[ap_const_lv32_16]);
end

always @ (*) begin
    ap_sig_323 = (1'b1 == ap_CS_fsm[ap_const_lv32_F]);
end

always @ (*) begin
    ap_sig_331 = (1'b1 == ap_CS_fsm[ap_const_lv32_17]);
end

always @ (*) begin
    ap_sig_344 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_351 = (1'b1 == ap_CS_fsm[ap_const_lv32_11]);
end

always @ (*) begin
    ap_sig_358 = (1'b1 == ap_CS_fsm[ap_const_lv32_19]);
end

always @ (*) begin
    ap_sig_48 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_87 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_94 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

assign exitcond11_fu_492_p2 = ((l_reg_205 == tmp_14_reg_674) ? 1'b1 : 1'b0);

assign exitcond1_fu_316_p2 = ((i_1_reg_160 == ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign exitcond_fu_460_p2 = ((m_reg_193 == ap_const_lv4_9) ? 1'b1 : 1'b0);

assign f_first_d1 = reg_258;

assign f_second_d1 = reg_267;

assign i_1_cast2_fu_312_p1 = i_1_reg_160;

assign j_7_fu_444_p2 = (k_reg_172 + j_1_reg_183);

assign j_8_fu_382_p2 = (j_1_reg_183 - k_reg_172);

assign k_5_fu_436_p3 = ((tmp_9_fu_388_p3[0:0] === 1'b1) ? p_neg_t_fu_416_p2 : tmp_50_fu_432_p1);

assign l_1_fu_581_p2 = (l_reg_205 + ap_const_lv8_1);

assign la_cast_fu_472_p1 = la_fu_466_p2;

assign la_fu_466_p2 = ap_const_lv9_1 << m_cast1_fu_456_p1;

assign m_1_fu_507_p2 = (m_reg_193 + ap_const_lv4_1);

assign m_cast1_fu_456_p1 = m_reg_193;

assign n_1_fu_576_p2 = (n1_reg_217 + la_cast_reg_664);

assign n_cast_fu_503_p1 = n_fu_497_p2;

assign n_fu_497_p2 = ($signed(l_reg_205) + $signed(ap_const_lv8_FF));

assign p_lshr_f1_cast_fu_476_p4 = {{la_fu_466_p2[ap_const_lv32_8 : ap_const_lv32_1]}};

assign p_lshr_f_fu_422_p4 = {{k_reg_172[ap_const_lv32_1F : ap_const_lv32_1]}};

assign p_lshr_fu_402_p4 = {{p_neg_fu_396_p2[ap_const_lv32_1F : ap_const_lv32_1]}};

assign p_neg_fu_396_p2 = (ap_const_lv32_0 - k_reg_172);

assign p_neg_t_fu_416_p2 = (ap_const_lv32_0 - tmp_49_fu_412_p1);

assign tmp_10_fu_519_p1 = n1_reg_217[14:0];

assign tmp_11_fu_523_p1 = p_lshr_f1_cast_reg_669;

assign tmp_12_fu_526_p2 = (tmp_11_fu_523_p1 + tmp_10_fu_519_p1);

assign tmp_13_fu_552_p1 = n1_reg_217[14:0];

assign tmp_14_fu_486_p2 = (p_lshr_f1_cast_fu_476_p4 + ap_const_lv8_1);

assign tmp_43_fu_332_p2 = (tmp_69_cast_reg_604 + tmp_6_fu_328_p1);

assign tmp_44_fu_342_p2 = (tmp_67_cast_reg_597 + tmp_6_fu_328_p1);

assign tmp_45_fu_359_p1 = tmp_7_fu_352_p3;

assign tmp_46_fu_371_p1 = tmp_8_fu_364_p3;

assign tmp_47_fu_376_p2 = (($signed(k_reg_172) > $signed(j_1_reg_183)) ? 1'b1 : 1'b0);

assign tmp_48_fu_450_p2 = (i_1_reg_160 + ap_const_lv8_1);

assign tmp_49_fu_412_p1 = p_lshr_fu_402_p4;

assign tmp_4_fu_288_p3 = {{tmp_1}, {ap_const_lv8_0}};

assign tmp_50_fu_432_p1 = p_lshr_f_fu_422_p4;

assign tmp_51_fu_513_p2 = (($signed(n1_reg_217) < $signed(32'b11111111)) ? 1'b1 : 1'b0);

assign tmp_52_fu_532_p2 = (tmp_69_cast_reg_604 + tmp_12_fu_526_p2);

assign tmp_53_fu_542_p2 = (tmp_67_cast_reg_597 + tmp_12_fu_526_p2);

assign tmp_54_fu_556_p2 = (tmp_69_cast_reg_604 + tmp_13_fu_552_p1);

assign tmp_55_fu_566_p2 = (tmp_67_cast_reg_597 + tmp_13_fu_552_p1);

assign tmp_5_fu_300_p3 = {{tmp_s}, {ap_const_lv8_0}};

assign tmp_67_cast_fu_296_p1 = tmp_4_fu_288_p3;

assign tmp_69_cast_fu_308_p1 = tmp_5_fu_300_p3;

assign tmp_6_fu_328_p1 = j_reg_148[14:0];

assign tmp_70_cast_fu_337_p1 = tmp_43_fu_332_p2;

assign tmp_71_cast_fu_347_p1 = tmp_44_fu_342_p2;

assign tmp_78_cast_fu_537_p1 = $signed(tmp_52_fu_532_p2);

assign tmp_79_cast_fu_547_p1 = $signed(tmp_53_fu_542_p2);

assign tmp_7_fu_352_p3 = {{tmp_s}, {i_1_reg_160}};

assign tmp_80_cast_fu_561_p1 = $signed(tmp_54_fu_556_p2);

assign tmp_81_cast_fu_571_p1 = $signed(tmp_55_fu_566_p2);

assign tmp_8_fu_364_p3 = {{tmp_1}, {i_1_reg_160}};

assign tmp_9_fu_388_p3 = k_reg_172[ap_const_lv32_1F];

assign tmp_fu_322_p2 = (($signed(i_1_cast2_fu_312_p1) < $signed(j_reg_148)) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_67_cast_reg_597[7:0] <= 8'b00000000;
    tmp_67_cast_reg_597[14] <= 1'b0;
    tmp_69_cast_reg_604[7:0] <= 8'b00000000;
    tmp_69_cast_reg_604[14] <= 1'b0;
    la_cast_reg_664[31:9] <= 23'b00000000000000000000000;
end

endmodule //dut_fft
