// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dut_HH_
#define _dut_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dut_mfcc.h"
#include "dut_fadd_32ns_32ns_32_5_full_dsp.h"
#include "dut_fdiv_32ns_32ns_32_16.h"
#include "dut_uitofp_64ns_32_6.h"
#include "dut_mfcc_M.h"

namespace ap_rtl {

struct dut : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > strm_in_V_V_dout;
    sc_in< sc_logic > strm_in_V_V_empty_n;
    sc_out< sc_logic > strm_in_V_V_read;
    sc_out< sc_lv<32> > strm_out_V_V_din;
    sc_in< sc_logic > strm_out_V_V_full_n;
    sc_out< sc_logic > strm_out_V_V_write;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<32> > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const2;


    // Module declarations
    dut(sc_module_name name);
    SC_HAS_PROCESS(dut);

    ~dut();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    dut_mfcc_M* sound_in_U;
    dut_mfcc* grp_dut_mfcc_fu_119;
    dut_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>* dut_fadd_32ns_32ns_32_5_full_dsp_U37;
    dut_fdiv_32ns_32ns_32_16<1,16,32,32,32>* dut_fdiv_32ns_32ns_32_16_U38;
    dut_uitofp_64ns_32_6<1,6,64,32>* dut_uitofp_64ns_32_6_U39;
    sc_signal< sc_lv<33> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_48;
    sc_signal< sc_logic > strm_in_V_V_blk_n;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_69;
    sc_signal< sc_lv<1> > exitcond_fu_153_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_80;
    sc_signal< sc_logic > strm_out_V_V_blk_n;
    sc_signal< sc_logic > ap_sig_cseq_ST_st32_fsm_31;
    sc_signal< bool > ap_sig_89;
    sc_signal< sc_logic > ap_sig_cseq_ST_st33_fsm_32;
    sc_signal< bool > ap_sig_96;
    sc_signal< sc_lv<14> > i_8_fu_159_p2;
    sc_signal< sc_lv<14> > i_8_reg_185;
    sc_signal< bool > ap_sig_103;
    sc_signal< sc_lv<32> > tmp_V_2_reg_190;
    sc_signal< sc_lv<32> > tmp_V_3_reg_196;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_119;
    sc_signal< sc_lv<32> > grp_fu_150_p1;
    sc_signal< sc_lv<32> > tmp_s_reg_206;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_128;
    sc_signal< sc_lv<32> > grp_fu_145_p2;
    sc_signal< sc_lv<32> > tmp_61_reg_211;
    sc_signal< sc_logic > ap_sig_cseq_ST_st25_fsm_24;
    sc_signal< bool > ap_sig_137;
    sc_signal< sc_lv<32> > grp_fu_140_p2;
    sc_signal< sc_lv<32> > tmp_62_reg_216;
    sc_signal< sc_logic > ap_sig_cseq_ST_st30_fsm_29;
    sc_signal< bool > ap_sig_146;
    sc_signal< sc_lv<14> > sound_in_address0;
    sc_signal< sc_logic > sound_in_ce0;
    sc_signal< sc_logic > sound_in_we0;
    sc_signal< sc_lv<32> > sound_in_q0;
    sc_signal< sc_logic > grp_dut_mfcc_fu_119_ap_start;
    sc_signal< sc_logic > grp_dut_mfcc_fu_119_ap_done;
    sc_signal< sc_logic > grp_dut_mfcc_fu_119_ap_idle;
    sc_signal< sc_logic > grp_dut_mfcc_fu_119_ap_ready;
    sc_signal< sc_lv<14> > grp_dut_mfcc_fu_119_sound_file_address0;
    sc_signal< sc_logic > grp_dut_mfcc_fu_119_sound_file_ce0;
    sc_signal< sc_lv<1> > grp_dut_mfcc_fu_119_ap_return;
    sc_signal< sc_lv<32> > tmp_V_1_reg_94;
    sc_signal< sc_logic > ap_sig_cseq_ST_st31_fsm_30;
    sc_signal< bool > ap_sig_175;
    sc_signal< sc_lv<14> > i_reg_107;
    sc_signal< sc_logic > ap_reg_grp_dut_mfcc_fu_119_ap_start;
    sc_signal< sc_lv<64> > tmp_63_fu_172_p1;
    sc_signal< sc_lv<32> > tmp_V_fu_177_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st26_fsm_25;
    sc_signal< bool > ap_sig_279;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_289;
    sc_signal< sc_lv<64> > grp_fu_150_p0;
    sc_signal< sc_lv<33> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<33> ap_ST_st1_fsm_0;
    static const sc_lv<33> ap_ST_st2_fsm_1;
    static const sc_lv<33> ap_ST_st3_fsm_2;
    static const sc_lv<33> ap_ST_st4_fsm_3;
    static const sc_lv<33> ap_ST_st5_fsm_4;
    static const sc_lv<33> ap_ST_st6_fsm_5;
    static const sc_lv<33> ap_ST_st7_fsm_6;
    static const sc_lv<33> ap_ST_st8_fsm_7;
    static const sc_lv<33> ap_ST_st9_fsm_8;
    static const sc_lv<33> ap_ST_st10_fsm_9;
    static const sc_lv<33> ap_ST_st11_fsm_10;
    static const sc_lv<33> ap_ST_st12_fsm_11;
    static const sc_lv<33> ap_ST_st13_fsm_12;
    static const sc_lv<33> ap_ST_st14_fsm_13;
    static const sc_lv<33> ap_ST_st15_fsm_14;
    static const sc_lv<33> ap_ST_st16_fsm_15;
    static const sc_lv<33> ap_ST_st17_fsm_16;
    static const sc_lv<33> ap_ST_st18_fsm_17;
    static const sc_lv<33> ap_ST_st19_fsm_18;
    static const sc_lv<33> ap_ST_st20_fsm_19;
    static const sc_lv<33> ap_ST_st21_fsm_20;
    static const sc_lv<33> ap_ST_st22_fsm_21;
    static const sc_lv<33> ap_ST_st23_fsm_22;
    static const sc_lv<33> ap_ST_st24_fsm_23;
    static const sc_lv<33> ap_ST_st25_fsm_24;
    static const sc_lv<33> ap_ST_st26_fsm_25;
    static const sc_lv<33> ap_ST_st27_fsm_26;
    static const sc_lv<33> ap_ST_st28_fsm_27;
    static const sc_lv<33> ap_ST_st29_fsm_28;
    static const sc_lv<33> ap_ST_st30_fsm_29;
    static const sc_lv<33> ap_ST_st31_fsm_30;
    static const sc_lv<33> ap_ST_st32_fsm_31;
    static const sc_lv<33> ap_ST_st33_fsm_32;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<32> ap_const_lv32_BF800000;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_47C35000;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<14> ap_const_lv14_3100;
    static const sc_lv<14> ap_const_lv14_1;
    // Thread declarations
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_103();
    void thread_ap_sig_119();
    void thread_ap_sig_128();
    void thread_ap_sig_137();
    void thread_ap_sig_146();
    void thread_ap_sig_175();
    void thread_ap_sig_279();
    void thread_ap_sig_289();
    void thread_ap_sig_48();
    void thread_ap_sig_69();
    void thread_ap_sig_80();
    void thread_ap_sig_89();
    void thread_ap_sig_96();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st25_fsm_24();
    void thread_ap_sig_cseq_ST_st26_fsm_25();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st30_fsm_29();
    void thread_ap_sig_cseq_ST_st31_fsm_30();
    void thread_ap_sig_cseq_ST_st32_fsm_31();
    void thread_ap_sig_cseq_ST_st33_fsm_32();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_exitcond_fu_153_p2();
    void thread_grp_dut_mfcc_fu_119_ap_start();
    void thread_grp_fu_150_p0();
    void thread_i_8_fu_159_p2();
    void thread_sound_in_address0();
    void thread_sound_in_ce0();
    void thread_sound_in_we0();
    void thread_strm_in_V_V_blk_n();
    void thread_strm_in_V_V_read();
    void thread_strm_out_V_V_blk_n();
    void thread_strm_out_V_V_din();
    void thread_strm_out_V_V_write();
    void thread_tmp_63_fu_172_p1();
    void thread_tmp_V_fu_177_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
