// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_knn.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_knn::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_knn::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<37> dut_knn::ap_ST_st1_fsm_0 = "1";
const sc_lv<37> dut_knn::ap_ST_st2_fsm_1 = "10";
const sc_lv<37> dut_knn::ap_ST_st3_fsm_2 = "100";
const sc_lv<37> dut_knn::ap_ST_st4_fsm_3 = "1000";
const sc_lv<37> dut_knn::ap_ST_st5_fsm_4 = "10000";
const sc_lv<37> dut_knn::ap_ST_st6_fsm_5 = "100000";
const sc_lv<37> dut_knn::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<37> dut_knn::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<37> dut_knn::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<37> dut_knn::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<37> dut_knn::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<37> dut_knn::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<37> dut_knn::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<37> dut_knn::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<37> dut_knn::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<37> dut_knn::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<37> dut_knn::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<37> dut_knn::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<37> dut_knn::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st25_fsm_24 = "1000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st26_fsm_25 = "10000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st27_fsm_26 = "100000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st28_fsm_27 = "1000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st29_fsm_28 = "10000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st30_fsm_29 = "100000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st31_fsm_30 = "1000000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st32_fsm_31 = "10000000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st33_fsm_32 = "100000000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st34_fsm_33 = "1000000000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st35_fsm_34 = "10000000000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st36_fsm_35 = "100000000000000000000000000000000000";
const sc_lv<37> dut_knn::ap_ST_st37_fsm_36 = "1000000000000000000000000000000000000";
const sc_lv<32> dut_knn::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_knn::ap_const_lv1_1 = "1";
const sc_lv<32> dut_knn::ap_const_lv32_1 = "1";
const sc_lv<1> dut_knn::ap_const_lv1_0 = "0";
const sc_lv<32> dut_knn::ap_const_lv32_2 = "10";
const sc_lv<32> dut_knn::ap_const_lv32_3 = "11";
const sc_lv<32> dut_knn::ap_const_lv32_4 = "100";
const sc_lv<32> dut_knn::ap_const_lv32_5 = "101";
const sc_lv<32> dut_knn::ap_const_lv32_A = "1010";
const sc_lv<32> dut_knn::ap_const_lv32_10 = "10000";
const sc_lv<32> dut_knn::ap_const_lv32_12 = "10010";
const sc_lv<32> dut_knn::ap_const_lv32_13 = "10011";
const sc_lv<32> dut_knn::ap_const_lv32_14 = "10100";
const sc_lv<32> dut_knn::ap_const_lv32_16 = "10110";
const sc_lv<32> dut_knn::ap_const_lv32_17 = "10111";
const sc_lv<32> dut_knn::ap_const_lv32_18 = "11000";
const sc_lv<32> dut_knn::ap_const_lv32_19 = "11001";
const sc_lv<32> dut_knn::ap_const_lv32_1E = "11110";
const sc_lv<32> dut_knn::ap_const_lv32_1F = "11111";
const sc_lv<32> dut_knn::ap_const_lv32_21 = "100001";
const sc_lv<32> dut_knn::ap_const_lv32_22 = "100010";
const sc_lv<32> dut_knn::ap_const_lv32_24 = "100100";
const sc_lv<4> dut_knn::ap_const_lv4_0 = "0000";
const sc_lv<32> dut_knn::ap_const_lv32_11 = "10001";
const sc_lv<9> dut_knn::ap_const_lv9_0 = "000000000";
const sc_lv<14> dut_knn::ap_const_lv14_0 = "00000000000000";
const sc_lv<5> dut_knn::ap_const_lv5_0 = "00000";
const sc_lv<10> dut_knn::ap_const_lv10_0 = "0000000000";
const sc_lv<32> dut_knn::ap_const_lv32_B = "1011";
const sc_lv<6> dut_knn::ap_const_lv6_0 = "000000";
const sc_lv<32> dut_knn::ap_const_lv32_15 = "10101";
const sc_lv<32> dut_knn::ap_const_lv32_23 = "100011";
const sc_lv<32> dut_knn::ap_const_lv32_20 = "100000";
const sc_lv<32> dut_knn::ap_const_lv32_1A = "11010";
const sc_lv<32> dut_knn::ap_const_lv32_3E4CCCCD = "111110010011001100110011001101";
const sc_lv<14> dut_knn::ap_const_lv14_3D5 = "1111010101";
const sc_lv<14> dut_knn::ap_const_lv14_3E8 = "1111101000";
const sc_lv<9> dut_knn::ap_const_lv9_13 = "10011";
const sc_lv<4> dut_knn::ap_const_lv4_E = "1110";
const sc_lv<4> dut_knn::ap_const_lv4_1 = "1";
const sc_lv<14> dut_knn::ap_const_lv14_3D4 = "1111010100";
const sc_lv<10> dut_knn::ap_const_lv10_32 = "110010";
const sc_lv<5> dut_knn::ap_const_lv5_14 = "10100";
const sc_lv<5> dut_knn::ap_const_lv5_1 = "1";
const sc_lv<32> dut_knn::ap_const_lv32_7 = "111";
const sc_lv<32> dut_knn::ap_const_lv32_8 = "1000";
const sc_lv<6> dut_knn::ap_const_lv6_31 = "110001";
const sc_lv<6> dut_knn::ap_const_lv6_1 = "1";
const sc_lv<14> dut_knn::ap_const_lv14_2AE = "1010101110";
const sc_lv<10> dut_knn::ap_const_lv10_31 = "110001";
const sc_lv<8> dut_knn::ap_const_lv8_FF = "11111111";
const sc_lv<23> dut_knn::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<9> dut_knn::ap_const_lv9_181 = "110000001";
const sc_lv<8> dut_knn::ap_const_lv8_7F = "1111111";
const sc_lv<32> dut_knn::ap_const_lv32_36 = "110110";
const sc_lv<5> dut_knn::ap_const_lv5_4 = "100";

dut_knn::dut_knn(sc_module_name name) : sc_module(name), mVcdFile(0) {
    training_data_V_U = new dut_knn_training_data_V("training_data_V_U");
    training_data_V_U->clk(ap_clk);
    training_data_V_U->reset(ap_rst);
    training_data_V_U->address0(training_data_V_address0);
    training_data_V_U->ce0(training_data_V_ce0);
    training_data_V_U->q0(training_data_V_q0);
    training_data2_U = new dut_knn_training_data2("training_data2_U");
    training_data2_U->clk(ap_clk);
    training_data2_U->reset(ap_rst);
    training_data2_U->address0(training_data2_address0);
    training_data2_U->ce0(training_data2_ce0);
    training_data2_U->we0(training_data2_we0);
    training_data2_U->d0(training_data2_d0);
    training_data2_U->q0(training_data2_q0);
    training_instance_U = new dut_knn_training_instance("training_instance_U");
    training_instance_U->clk(ap_clk);
    training_instance_U->reset(ap_rst);
    training_instance_U->address0(training_instance_address0);
    training_instance_U->ce0(training_instance_ce0);
    training_instance_U->we0(training_instance_we0);
    training_instance_U->d0(training_data2_q0);
    training_instance_U->q0(training_instance_q0);
    min_distance_U = new dut_knn_min_distance("min_distance_U");
    min_distance_U->clk(ap_clk);
    min_distance_U->reset(ap_rst);
    min_distance_U->address0(min_distance_addr_reg_1296);
    min_distance_U->ce0(min_distance_ce0);
    min_distance_U->we0(min_distance_we0);
    min_distance_U->d0(distance_q0);
    min_distance_U->q0(min_distance_q0);
    distance_U = new dut_knn_distance("distance_U");
    distance_U->clk(ap_clk);
    distance_U->reset(ap_rst);
    distance_U->address0(distance_addr_reg_1329);
    distance_U->ce0(distance_ce0);
    distance_U->we0(distance_we0);
    distance_U->d0(distance_d0);
    distance_U->q0(distance_q0);
    group_U = new dut_knn_min_distance("group_U");
    group_U->clk(ap_clk);
    group_U->reset(ap_rst);
    group_U->address0(group_addr_reg_1301);
    group_U->ce0(group_ce0);
    group_U->we0(group_we0);
    group_U->d0(group_d0);
    group_U->q0(group_q0);
    dut_fsub_32ns_32ns_32_5_full_dsp_U13 = new dut_fsub_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dut_fsub_32ns_32ns_32_5_full_dsp_U13");
    dut_fsub_32ns_32ns_32_5_full_dsp_U13->clk(ap_clk);
    dut_fsub_32ns_32ns_32_5_full_dsp_U13->reset(ap_rst);
    dut_fsub_32ns_32ns_32_5_full_dsp_U13->din0(input_load_reg_1357);
    dut_fsub_32ns_32ns_32_5_full_dsp_U13->din1(training_instance_load_reg_1362);
    dut_fsub_32ns_32ns_32_5_full_dsp_U13->ce(ap_var_for_const0);
    dut_fsub_32ns_32ns_32_5_full_dsp_U13->dout(grp_fu_500_p2);
    dut_uitofp_32ns_32_6_U14 = new dut_uitofp_32ns_32_6<1,6,32,32>("dut_uitofp_32ns_32_6_U14");
    dut_uitofp_32ns_32_6_U14->clk(ap_clk);
    dut_uitofp_32ns_32_6_U14->reset(ap_rst);
    dut_uitofp_32ns_32_6_U14->din0(grp_fu_504_p0);
    dut_uitofp_32ns_32_6_U14->ce(ap_var_for_const0);
    dut_uitofp_32ns_32_6_U14->dout(grp_fu_504_p1);
    dut_sitofp_32ns_32_6_U15 = new dut_sitofp_32ns_32_6<1,6,32,32>("dut_sitofp_32ns_32_6_U15");
    dut_sitofp_32ns_32_6_U15->clk(ap_clk);
    dut_sitofp_32ns_32_6_U15->reset(ap_rst);
    dut_sitofp_32ns_32_6_U15->din0(grp_fu_507_p0);
    dut_sitofp_32ns_32_6_U15->ce(ap_var_for_const0);
    dut_sitofp_32ns_32_6_U15->dout(grp_fu_507_p1);
    dut_fcmp_32ns_32ns_1_1_U16 = new dut_fcmp_32ns_32ns_1_1<1,1,32,32,1>("dut_fcmp_32ns_32ns_1_1_U16");
    dut_fcmp_32ns_32ns_1_1_U16->din0(tmp_5_fu_510_p0);
    dut_fcmp_32ns_32ns_1_1_U16->din1(ap_var_for_const1);
    dut_fcmp_32ns_32ns_1_1_U16->opcode(ap_var_for_const2);
    dut_fcmp_32ns_32ns_1_1_U16->dout(tmp_5_fu_510_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( exitcond4_fu_760_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( exitcond4_fu_760_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( exitcond4_fu_760_p2 );
    sensitive << ( rev_fu_784_p2 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_101);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_120);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_137);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_146);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_155);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_164);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_173);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_186);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_199);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_219);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_239);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_259);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_276);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_287);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_296);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_305);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_314);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_325);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_388);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_413);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_445);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_471);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_482);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_529);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_54);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_80);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_155 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_413 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_164 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_388 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_173 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_54 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_186 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_199 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_445 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_219 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_239 );

    SC_METHOD(thread_ap_sig_cseq_ST_st25_fsm_24);
    sensitive << ( ap_sig_259 );

    SC_METHOD(thread_ap_sig_cseq_ST_st26_fsm_25);
    sensitive << ( ap_sig_276 );

    SC_METHOD(thread_ap_sig_cseq_ST_st27_fsm_26);
    sensitive << ( ap_sig_529 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_80 );

    SC_METHOD(thread_ap_sig_cseq_ST_st31_fsm_30);
    sensitive << ( ap_sig_287 );

    SC_METHOD(thread_ap_sig_cseq_ST_st32_fsm_31);
    sensitive << ( ap_sig_296 );

    SC_METHOD(thread_ap_sig_cseq_ST_st33_fsm_32);
    sensitive << ( ap_sig_482 );

    SC_METHOD(thread_ap_sig_cseq_ST_st34_fsm_33);
    sensitive << ( ap_sig_305 );

    SC_METHOD(thread_ap_sig_cseq_ST_st35_fsm_34);
    sensitive << ( ap_sig_314 );

    SC_METHOD(thread_ap_sig_cseq_ST_st36_fsm_35);
    sensitive << ( ap_sig_471 );

    SC_METHOD(thread_ap_sig_cseq_ST_st37_fsm_36);
    sensitive << ( ap_sig_325 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_101 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_120 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_146 );

    SC_METHOD(thread_distance_ce0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( ap_sig_cseq_ST_st33_fsm_32 );

    SC_METHOD(thread_distance_d0);
    sensitive << ( distance_q0 );
    sensitive << ( ap_sig_cseq_ST_st33_fsm_32 );

    SC_METHOD(thread_distance_we0);
    sensitive << ( tmp_6_reg_1372 );
    sensitive << ( ap_sig_cseq_ST_st33_fsm_32 );

    SC_METHOD(thread_exitcond10_fu_533_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( j_reg_226 );

    SC_METHOD(thread_exitcond3_fu_800_p2);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( j5_reg_456 );

    SC_METHOD(thread_exitcond4_fu_760_p2);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( i4_reg_421 );

    SC_METHOD(thread_exitcond5_fu_697_p2);
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( k3_reg_364 );

    SC_METHOD(thread_exitcond6_fu_685_p2);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( j2_reg_341 );

    SC_METHOD(thread_exitcond7_fu_663_p2);
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( i1_reg_318 );

    SC_METHOD(thread_exitcond8_fu_597_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( k_reg_296 );

    SC_METHOD(thread_exitcond9_fu_566_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_reg_273 );

    SC_METHOD(thread_exitcond_fu_828_p2);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( k6_reg_478 );

    SC_METHOD(thread_group_ce0);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st36_fsm_35 );

    SC_METHOD(thread_group_d0);
    sensitive << ( p_Result_20_reg_1380 );
    sensitive << ( p_Val2_28_reg_1385 );
    sensitive << ( ap_sig_cseq_ST_st36_fsm_35 );
    sensitive << ( p_Val2_i_i_fu_1074_p2 );

    SC_METHOD(thread_group_one_1_fu_1112_p3);
    sensitive << ( group_one_s_reg_409 );
    sensitive << ( tmp_50_fu_1086_p2 );
    sensitive << ( group_one_fu_1098_p2 );

    SC_METHOD(thread_group_one_fu_1098_p2);
    sensitive << ( group_one_s_reg_409 );

    SC_METHOD(thread_group_we0);
    sensitive << ( tmp_57_reg_1376 );
    sensitive << ( ap_sig_cseq_ST_st36_fsm_35 );

    SC_METHOD(thread_group_zero_1_fu_1104_p3);
    sensitive << ( group_zero_s_reg_397 );
    sensitive << ( tmp_50_fu_1086_p2 );
    sensitive << ( group_zero_fu_1092_p2 );

    SC_METHOD(thread_group_zero_fu_1092_p2);
    sensitive << ( group_zero_s_reg_397 );

    SC_METHOD(thread_grp_fu_504_p0);
    sensitive << ( training_data_V_load_reg_1194 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_fu_507_p0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_fu_578_p4 );

    SC_METHOD(thread_i1_cast_cast_fu_659_p1);
    sensitive << ( i1_reg_318 );

    SC_METHOD(thread_i_5_fu_669_p2);
    sensitive << ( i1_reg_318 );

    SC_METHOD(thread_i_6_fu_572_p2);
    sensitive << ( i_reg_273 );

    SC_METHOD(thread_i_7_fu_766_p2);
    sensitive << ( i4_reg_421 );

    SC_METHOD(thread_i_cast_cast_fu_562_p1);
    sensitive << ( i_reg_273 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( tmp_73_cast_fu_850_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_isNeg_fu_994_p3);
    sensitive << ( sh_assign_fu_988_p2 );

    SC_METHOD(thread_j2_cast_fu_681_p1);
    sensitive << ( j2_reg_341 );

    SC_METHOD(thread_j5_cast6_fu_796_p1);
    sensitive << ( j5_reg_456 );

    SC_METHOD(thread_j_6_fu_539_p2);
    sensitive << ( j_reg_226 );

    SC_METHOD(thread_j_7_fu_691_p2);
    sensitive << ( j2_reg_341 );

    SC_METHOD(thread_j_8_fu_806_p2);
    sensitive << ( j5_reg_456 );

    SC_METHOD(thread_k_2_fu_603_p2);
    sensitive << ( k_reg_296 );

    SC_METHOD(thread_k_3_fu_703_p2);
    sensitive << ( k3_reg_364 );

    SC_METHOD(thread_k_4_fu_834_p2);
    sensitive << ( k6_reg_478 );

    SC_METHOD(thread_k_cast1_fu_593_p1);
    sensitive << ( k_reg_296 );

    SC_METHOD(thread_loc_V_2_fu_968_p1);
    sensitive << ( p_Val2_25_fu_946_p1 );

    SC_METHOD(thread_loc_V_fu_958_p4);
    sensitive << ( p_Val2_25_fu_946_p1 );

    SC_METHOD(thread_min_distance_ce0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );

    SC_METHOD(thread_min_distance_we0);
    sensitive << ( tmp_57_fu_940_p2 );
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );

    SC_METHOD(thread_next_mul10_fu_709_p2);
    sensitive << ( i1_cast_cast_reg_1219 );
    sensitive << ( phi_mul9_reg_375 );

    SC_METHOD(thread_next_mul11_fu_790_p2);
    sensitive << ( phi_mul11_reg_467 );

    SC_METHOD(thread_next_mul12_fu_729_p2);
    sensitive << ( j2_cast_reg_1237 );
    sensitive << ( phi_mul10_reg_386 );

    SC_METHOD(thread_next_mul13_fu_855_p2);
    sensitive << ( j5_cast6_reg_1311 );
    sensitive << ( phi_mul12_reg_489 );

    SC_METHOD(thread_next_mul2_fu_556_p2);
    sensitive << ( phi_mul1_reg_284 );

    SC_METHOD(thread_next_mul3_fu_653_p2);
    sensitive << ( phi_mul2_reg_329 );

    SC_METHOD(thread_next_mul4_fu_527_p2);
    sensitive << ( phi_mul3_reg_237 );

    SC_METHOD(thread_next_mul5_fu_748_p2);
    sensitive << ( phi_mul6_reg_444 );

    SC_METHOD(thread_next_mul6_fu_521_p2);
    sensitive << ( phi_mul5_reg_249 );

    SC_METHOD(thread_next_mul7_fu_754_p2);
    sensitive << ( phi_mul4_reg_432 );

    SC_METHOD(thread_next_mul8_fu_515_p2);
    sensitive << ( phi_mul7_reg_261 );

    SC_METHOD(thread_next_mul9_fu_675_p2);
    sensitive << ( phi_mul8_reg_352 );

    SC_METHOD(thread_next_mul_fu_630_p2);
    sensitive << ( i_cast_cast_reg_1153 );
    sensitive << ( phi_mul_reg_307 );

    SC_METHOD(thread_notlhs_fu_909_p2);
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( tmp_3_fu_899_p4 );

    SC_METHOD(thread_notrhs_fu_915_p2);
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( tmp_60_fu_882_p1 );

    SC_METHOD(thread_p_Result_21_fu_972_p3);
    sensitive << ( loc_V_2_fu_968_p1 );

    SC_METHOD(thread_p_Result_s_fu_886_p3);
    sensitive << ( tmp_49_fu_878_p1 );

    SC_METHOD(thread_p_Val2_25_fu_946_p1);
    sensitive << ( training_data2_q0 );

    SC_METHOD(thread_p_Val2_28_fu_1066_p3);
    sensitive << ( isNeg_fu_994_p3 );
    sensitive << ( tmp_62_fu_1052_p1 );
    sensitive << ( tmp_63_fu_1056_p4 );

    SC_METHOD(thread_p_Val2_i_i_fu_1074_p2);
    sensitive << ( p_Val2_28_reg_1385 );

    SC_METHOD(thread_p_Val2_s_fu_875_p1);
    sensitive << ( p_x_assign_reg_1367 );

    SC_METHOD(thread_rev_fu_784_p2);
    sensitive << ( slt_fu_778_p2 );

    SC_METHOD(thread_sh_assign_1_cast_cast_fu_1024_p1);
    sensitive << ( sh_assign_1_fu_1012_p3 );

    SC_METHOD(thread_sh_assign_1_cast_fu_1020_p1);
    sensitive << ( sh_assign_1_fu_1012_p3 );

    SC_METHOD(thread_sh_assign_1_fu_1012_p3);
    sensitive << ( sh_assign_fu_988_p2 );
    sensitive << ( isNeg_fu_994_p3 );
    sensitive << ( tmp_117_i_i_cast_fu_1008_p1 );

    SC_METHOD(thread_sh_assign_fu_988_p2);
    sensitive << ( tmp_i_i_i_cast2_fu_984_p1 );

    SC_METHOD(thread_slt_fu_778_p2);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( exitcond4_fu_760_p2 );
    sensitive << ( group_zero_s_reg_397 );
    sensitive << ( group_one_s_reg_409 );

    SC_METHOD(thread_tmp1_cast_fu_615_p1);
    sensitive << ( tmp1_fu_609_p2 );

    SC_METHOD(thread_tmp1_fu_609_p2);
    sensitive << ( phi_mul1_reg_284 );
    sensitive << ( k_cast1_fu_593_p1 );

    SC_METHOD(thread_tmp_117_i_i_cast_fu_1008_p1);
    sensitive << ( tmp_117_i_i_fu_1002_p2 );

    SC_METHOD(thread_tmp_117_i_i_fu_1002_p2);
    sensitive << ( loc_V_fu_958_p4 );

    SC_METHOD(thread_tmp_118_i_i_fu_1028_p1);
    sensitive << ( sh_assign_1_cast_fu_1020_p1 );

    SC_METHOD(thread_tmp_119_i_i_fu_1032_p2);
    sensitive << ( p_Result_21_fu_972_p3 );
    sensitive << ( sh_assign_1_cast_cast_fu_1024_p1 );

    SC_METHOD(thread_tmp_121_i_i_fu_1038_p2);
    sensitive << ( tmp_i_i_fu_980_p1 );
    sensitive << ( tmp_118_i_i_fu_1028_p1 );

    SC_METHOD(thread_tmp_3_fu_899_p4);
    sensitive << ( p_Val2_s_fu_875_p1 );

    SC_METHOD(thread_tmp_44_fu_772_p1);
    sensitive << ( i4_reg_421 );

    SC_METHOD(thread_tmp_46_fu_619_p2);
    sensitive << ( phi_mul5_reg_249 );
    sensitive << ( tmp1_cast_fu_615_p1 );

    SC_METHOD(thread_tmp_47_fu_625_p1);
    sensitive << ( tmp_46_fu_619_p2 );

    SC_METHOD(thread_tmp_49_fu_878_p1);
    sensitive << ( p_Val2_s_fu_875_p1 );

    SC_METHOD(thread_tmp_4_fu_921_p2);
    sensitive << ( notrhs_fu_915_p2 );
    sensitive << ( notlhs_fu_909_p2 );

    SC_METHOD(thread_tmp_50_fu_1086_p2);
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( group_q0 );

    SC_METHOD(thread_tmp_51_fu_812_p1);
    sensitive << ( j5_reg_456 );

    SC_METHOD(thread_tmp_52_cast_fu_635_p1);
    sensitive << ( phi_mul_reg_307 );

    SC_METHOD(thread_tmp_52_fu_718_p2);
    sensitive << ( phi_mul8_reg_352 );
    sensitive << ( tmp_54_cast_fu_714_p1 );

    SC_METHOD(thread_tmp_53_fu_738_p2);
    sensitive << ( phi_mul2_reg_329 );
    sensitive << ( tmp_56_cast_fu_734_p1 );

    SC_METHOD(thread_tmp_54_cast_fu_714_p1);
    sensitive << ( phi_mul9_reg_375 );

    SC_METHOD(thread_tmp_55_fu_639_p2);
    sensitive << ( phi_mul7_reg_261 );
    sensitive << ( tmp_52_cast_fu_635_p1 );

    SC_METHOD(thread_tmp_56_cast_fu_734_p1);
    sensitive << ( phi_mul10_reg_386 );

    SC_METHOD(thread_tmp_56_fu_817_p2);
    sensitive << ( phi_mul11_reg_467 );

    SC_METHOD(thread_tmp_57_fu_940_p2);
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );
    sensitive << ( min_distance_q0 );
    sensitive << ( distance_q0 );

    SC_METHOD(thread_tmp_58_cast_fu_840_p1);
    sensitive << ( k6_reg_478 );

    SC_METHOD(thread_tmp_58_fu_844_p2);
    sensitive << ( phi_mul4_reg_432 );
    sensitive << ( tmp_58_cast_fu_840_p1 );

    SC_METHOD(thread_tmp_59_fu_864_p2);
    sensitive << ( phi_mul6_reg_444 );
    sensitive << ( tmp_60_cast_fu_860_p1 );

    SC_METHOD(thread_tmp_5_fu_510_p0);
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( p_Result_s_fu_886_p3 );

    SC_METHOD(thread_tmp_60_cast_fu_860_p1);
    sensitive << ( phi_mul12_reg_489 );

    SC_METHOD(thread_tmp_60_fu_882_p1);
    sensitive << ( p_Val2_s_fu_875_p1 );

    SC_METHOD(thread_tmp_62_fu_1052_p1);
    sensitive << ( tmp_65_fu_1044_p3 );

    SC_METHOD(thread_tmp_63_cast_fu_551_p1);
    sensitive << ( tmp_s_fu_545_p2 );

    SC_METHOD(thread_tmp_63_fu_1056_p4);
    sensitive << ( tmp_121_i_i_fu_1038_p2 );

    SC_METHOD(thread_tmp_65_fu_1044_p3);
    sensitive << ( tmp_119_i_i_fu_1032_p2 );

    SC_METHOD(thread_tmp_68_cast_fu_649_p1);
    sensitive << ( tmp_55_reg_1189 );

    SC_METHOD(thread_tmp_6_fu_927_p2);
    sensitive << ( tmp_4_fu_921_p2 );
    sensitive << ( tmp_5_fu_510_p2 );

    SC_METHOD(thread_tmp_70_cast_fu_823_p1);
    sensitive << ( tmp_56_fu_817_p2 );

    SC_METHOD(thread_tmp_71_cast_fu_724_p1);
    sensitive << ( tmp_52_fu_718_p2 );

    SC_METHOD(thread_tmp_72_cast_fu_744_p1);
    sensitive << ( tmp_53_reg_1273 );

    SC_METHOD(thread_tmp_73_cast_fu_850_p1);
    sensitive << ( tmp_58_fu_844_p2 );

    SC_METHOD(thread_tmp_74_cast_fu_870_p1);
    sensitive << ( tmp_59_fu_864_p2 );

    SC_METHOD(thread_tmp_fu_578_p4);
    sensitive << ( phi_mul3_reg_237 );

    SC_METHOD(thread_tmp_i_i_fu_980_p1);
    sensitive << ( p_Result_21_fu_972_p3 );

    SC_METHOD(thread_tmp_i_i_i_cast2_fu_984_p1);
    sensitive << ( loc_V_fu_958_p4 );

    SC_METHOD(thread_tmp_s_fu_545_p2);
    sensitive << ( phi_mul7_reg_261 );

    SC_METHOD(thread_training_data2_address0);
    sensitive << ( training_data2_addr_reg_1143 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( training_data2_addr_3_reg_1324 );
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_68_cast_fu_649_p1 );
    sensitive << ( tmp_71_cast_fu_724_p1 );

    SC_METHOD(thread_training_data2_ce0);
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_training_data2_d0);
    sensitive << ( tmp_48_reg_1204 );
    sensitive << ( tmp_42_reg_1209 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_training_data2_we0);
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_training_data_V_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_47_fu_625_p1 );

    SC_METHOD(thread_training_data_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_training_instance_address0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( tmp_72_cast_fu_744_p1 );
    sensitive << ( tmp_74_cast_fu_870_p1 );

    SC_METHOD(thread_training_instance_ce0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_training_instance_we0);
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond10_fu_533_p2 );
    sensitive << ( exitcond9_fu_566_p2 );
    sensitive << ( exitcond8_fu_597_p2 );
    sensitive << ( exitcond5_fu_697_p2 );
    sensitive << ( exitcond4_fu_760_p2 );
    sensitive << ( exitcond3_fu_800_p2 );
    sensitive << ( exitcond_fu_828_p2 );
    sensitive << ( tmp_57_fu_940_p2 );
    sensitive << ( exitcond6_fu_685_p2 );
    sensitive << ( exitcond7_fu_663_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "0000000000000000000000000000000000001";
    ap_return_preg = "0";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_knn_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_54, "ap_sig_54");
    sc_trace(mVcdFile, training_data_V_address0, "training_data_V_address0");
    sc_trace(mVcdFile, training_data_V_ce0, "training_data_V_ce0");
    sc_trace(mVcdFile, training_data_V_q0, "training_data_V_q0");
    sc_trace(mVcdFile, next_mul8_fu_515_p2, "next_mul8_fu_515_p2");
    sc_trace(mVcdFile, next_mul8_reg_1120, "next_mul8_reg_1120");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_80, "ap_sig_80");
    sc_trace(mVcdFile, next_mul6_fu_521_p2, "next_mul6_fu_521_p2");
    sc_trace(mVcdFile, next_mul6_reg_1125, "next_mul6_reg_1125");
    sc_trace(mVcdFile, next_mul4_fu_527_p2, "next_mul4_fu_527_p2");
    sc_trace(mVcdFile, next_mul4_reg_1130, "next_mul4_reg_1130");
    sc_trace(mVcdFile, j_6_fu_539_p2, "j_6_fu_539_p2");
    sc_trace(mVcdFile, j_6_reg_1138, "j_6_reg_1138");
    sc_trace(mVcdFile, training_data2_addr_reg_1143, "training_data2_addr_reg_1143");
    sc_trace(mVcdFile, exitcond10_fu_533_p2, "exitcond10_fu_533_p2");
    sc_trace(mVcdFile, next_mul2_fu_556_p2, "next_mul2_fu_556_p2");
    sc_trace(mVcdFile, next_mul2_reg_1148, "next_mul2_reg_1148");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_101, "ap_sig_101");
    sc_trace(mVcdFile, i_cast_cast_fu_562_p1, "i_cast_cast_fu_562_p1");
    sc_trace(mVcdFile, i_cast_cast_reg_1153, "i_cast_cast_reg_1153");
    sc_trace(mVcdFile, i_6_fu_572_p2, "i_6_fu_572_p2");
    sc_trace(mVcdFile, i_6_reg_1161, "i_6_reg_1161");
    sc_trace(mVcdFile, exitcond9_fu_566_p2, "exitcond9_fu_566_p2");
    sc_trace(mVcdFile, k_2_fu_603_p2, "k_2_fu_603_p2");
    sc_trace(mVcdFile, k_2_reg_1174, "k_2_reg_1174");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_120, "ap_sig_120");
    sc_trace(mVcdFile, exitcond8_fu_597_p2, "exitcond8_fu_597_p2");
    sc_trace(mVcdFile, next_mul_fu_630_p2, "next_mul_fu_630_p2");
    sc_trace(mVcdFile, next_mul_reg_1184, "next_mul_reg_1184");
    sc_trace(mVcdFile, tmp_55_fu_639_p2, "tmp_55_fu_639_p2");
    sc_trace(mVcdFile, tmp_55_reg_1189, "tmp_55_reg_1189");
    sc_trace(mVcdFile, training_data_V_load_reg_1194, "training_data_V_load_reg_1194");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_137, "ap_sig_137");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_146, "ap_sig_146");
    sc_trace(mVcdFile, grp_fu_504_p1, "grp_fu_504_p1");
    sc_trace(mVcdFile, tmp_48_reg_1204, "tmp_48_reg_1204");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_155, "ap_sig_155");
    sc_trace(mVcdFile, grp_fu_507_p1, "grp_fu_507_p1");
    sc_trace(mVcdFile, tmp_42_reg_1209, "tmp_42_reg_1209");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_164, "ap_sig_164");
    sc_trace(mVcdFile, next_mul3_fu_653_p2, "next_mul3_fu_653_p2");
    sc_trace(mVcdFile, next_mul3_reg_1214, "next_mul3_reg_1214");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_173, "ap_sig_173");
    sc_trace(mVcdFile, i1_cast_cast_fu_659_p1, "i1_cast_cast_fu_659_p1");
    sc_trace(mVcdFile, i1_cast_cast_reg_1219, "i1_cast_cast_reg_1219");
    sc_trace(mVcdFile, i_5_fu_669_p2, "i_5_fu_669_p2");
    sc_trace(mVcdFile, i_5_reg_1227, "i_5_reg_1227");
    sc_trace(mVcdFile, next_mul9_fu_675_p2, "next_mul9_fu_675_p2");
    sc_trace(mVcdFile, next_mul9_reg_1232, "next_mul9_reg_1232");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_186, "ap_sig_186");
    sc_trace(mVcdFile, j2_cast_fu_681_p1, "j2_cast_fu_681_p1");
    sc_trace(mVcdFile, j2_cast_reg_1237, "j2_cast_reg_1237");
    sc_trace(mVcdFile, j_7_fu_691_p2, "j_7_fu_691_p2");
    sc_trace(mVcdFile, j_7_reg_1245, "j_7_reg_1245");
    sc_trace(mVcdFile, k_3_fu_703_p2, "k_3_fu_703_p2");
    sc_trace(mVcdFile, k_3_reg_1253, "k_3_reg_1253");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_199, "ap_sig_199");
    sc_trace(mVcdFile, next_mul10_fu_709_p2, "next_mul10_fu_709_p2");
    sc_trace(mVcdFile, next_mul10_reg_1258, "next_mul10_reg_1258");
    sc_trace(mVcdFile, exitcond5_fu_697_p2, "exitcond5_fu_697_p2");
    sc_trace(mVcdFile, next_mul12_fu_729_p2, "next_mul12_fu_729_p2");
    sc_trace(mVcdFile, next_mul12_reg_1268, "next_mul12_reg_1268");
    sc_trace(mVcdFile, tmp_53_fu_738_p2, "tmp_53_fu_738_p2");
    sc_trace(mVcdFile, tmp_53_reg_1273, "tmp_53_reg_1273");
    sc_trace(mVcdFile, next_mul5_fu_748_p2, "next_mul5_fu_748_p2");
    sc_trace(mVcdFile, next_mul5_reg_1278, "next_mul5_reg_1278");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_219, "ap_sig_219");
    sc_trace(mVcdFile, next_mul7_fu_754_p2, "next_mul7_fu_754_p2");
    sc_trace(mVcdFile, next_mul7_reg_1283, "next_mul7_reg_1283");
    sc_trace(mVcdFile, i_7_fu_766_p2, "i_7_fu_766_p2");
    sc_trace(mVcdFile, i_7_reg_1291, "i_7_reg_1291");
    sc_trace(mVcdFile, min_distance_addr_reg_1296, "min_distance_addr_reg_1296");
    sc_trace(mVcdFile, exitcond4_fu_760_p2, "exitcond4_fu_760_p2");
    sc_trace(mVcdFile, group_addr_reg_1301, "group_addr_reg_1301");
    sc_trace(mVcdFile, next_mul11_fu_790_p2, "next_mul11_fu_790_p2");
    sc_trace(mVcdFile, next_mul11_reg_1306, "next_mul11_reg_1306");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_239, "ap_sig_239");
    sc_trace(mVcdFile, j5_cast6_fu_796_p1, "j5_cast6_fu_796_p1");
    sc_trace(mVcdFile, j5_cast6_reg_1311, "j5_cast6_reg_1311");
    sc_trace(mVcdFile, j_8_fu_806_p2, "j_8_fu_806_p2");
    sc_trace(mVcdFile, j_8_reg_1319, "j_8_reg_1319");
    sc_trace(mVcdFile, training_data2_addr_3_reg_1324, "training_data2_addr_3_reg_1324");
    sc_trace(mVcdFile, exitcond3_fu_800_p2, "exitcond3_fu_800_p2");
    sc_trace(mVcdFile, distance_addr_reg_1329, "distance_addr_reg_1329");
    sc_trace(mVcdFile, k_4_fu_834_p2, "k_4_fu_834_p2");
    sc_trace(mVcdFile, k_4_reg_1337, "k_4_reg_1337");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st25_fsm_24, "ap_sig_cseq_ST_st25_fsm_24");
    sc_trace(mVcdFile, ap_sig_259, "ap_sig_259");
    sc_trace(mVcdFile, exitcond_fu_828_p2, "exitcond_fu_828_p2");
    sc_trace(mVcdFile, next_mul13_fu_855_p2, "next_mul13_fu_855_p2");
    sc_trace(mVcdFile, next_mul13_reg_1347, "next_mul13_reg_1347");
    sc_trace(mVcdFile, input_load_reg_1357, "input_load_reg_1357");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st26_fsm_25, "ap_sig_cseq_ST_st26_fsm_25");
    sc_trace(mVcdFile, ap_sig_276, "ap_sig_276");
    sc_trace(mVcdFile, training_instance_q0, "training_instance_q0");
    sc_trace(mVcdFile, training_instance_load_reg_1362, "training_instance_load_reg_1362");
    sc_trace(mVcdFile, grp_fu_500_p2, "grp_fu_500_p2");
    sc_trace(mVcdFile, p_x_assign_reg_1367, "p_x_assign_reg_1367");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st31_fsm_30, "ap_sig_cseq_ST_st31_fsm_30");
    sc_trace(mVcdFile, ap_sig_287, "ap_sig_287");
    sc_trace(mVcdFile, tmp_6_fu_927_p2, "tmp_6_fu_927_p2");
    sc_trace(mVcdFile, tmp_6_reg_1372, "tmp_6_reg_1372");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st32_fsm_31, "ap_sig_cseq_ST_st32_fsm_31");
    sc_trace(mVcdFile, ap_sig_296, "ap_sig_296");
    sc_trace(mVcdFile, tmp_57_fu_940_p2, "tmp_57_fu_940_p2");
    sc_trace(mVcdFile, tmp_57_reg_1376, "tmp_57_reg_1376");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st34_fsm_33, "ap_sig_cseq_ST_st34_fsm_33");
    sc_trace(mVcdFile, ap_sig_305, "ap_sig_305");
    sc_trace(mVcdFile, p_Result_20_reg_1380, "p_Result_20_reg_1380");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st35_fsm_34, "ap_sig_cseq_ST_st35_fsm_34");
    sc_trace(mVcdFile, ap_sig_314, "ap_sig_314");
    sc_trace(mVcdFile, p_Val2_28_fu_1066_p3, "p_Val2_28_fu_1066_p3");
    sc_trace(mVcdFile, p_Val2_28_reg_1385, "p_Val2_28_reg_1385");
    sc_trace(mVcdFile, group_zero_1_fu_1104_p3, "group_zero_1_fu_1104_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st37_fsm_36, "ap_sig_cseq_ST_st37_fsm_36");
    sc_trace(mVcdFile, ap_sig_325, "ap_sig_325");
    sc_trace(mVcdFile, group_one_1_fu_1112_p3, "group_one_1_fu_1112_p3");
    sc_trace(mVcdFile, training_data2_address0, "training_data2_address0");
    sc_trace(mVcdFile, training_data2_ce0, "training_data2_ce0");
    sc_trace(mVcdFile, training_data2_we0, "training_data2_we0");
    sc_trace(mVcdFile, training_data2_d0, "training_data2_d0");
    sc_trace(mVcdFile, training_data2_q0, "training_data2_q0");
    sc_trace(mVcdFile, training_instance_address0, "training_instance_address0");
    sc_trace(mVcdFile, training_instance_ce0, "training_instance_ce0");
    sc_trace(mVcdFile, training_instance_we0, "training_instance_we0");
    sc_trace(mVcdFile, min_distance_ce0, "min_distance_ce0");
    sc_trace(mVcdFile, min_distance_we0, "min_distance_we0");
    sc_trace(mVcdFile, min_distance_q0, "min_distance_q0");
    sc_trace(mVcdFile, distance_ce0, "distance_ce0");
    sc_trace(mVcdFile, distance_we0, "distance_we0");
    sc_trace(mVcdFile, distance_d0, "distance_d0");
    sc_trace(mVcdFile, distance_q0, "distance_q0");
    sc_trace(mVcdFile, group_ce0, "group_ce0");
    sc_trace(mVcdFile, group_we0, "group_we0");
    sc_trace(mVcdFile, group_d0, "group_d0");
    sc_trace(mVcdFile, group_q0, "group_q0");
    sc_trace(mVcdFile, j_reg_226, "j_reg_226");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_388, "ap_sig_388");
    sc_trace(mVcdFile, phi_mul3_reg_237, "phi_mul3_reg_237");
    sc_trace(mVcdFile, phi_mul5_reg_249, "phi_mul5_reg_249");
    sc_trace(mVcdFile, phi_mul7_reg_261, "phi_mul7_reg_261");
    sc_trace(mVcdFile, i_reg_273, "i_reg_273");
    sc_trace(mVcdFile, phi_mul1_reg_284, "phi_mul1_reg_284");
    sc_trace(mVcdFile, k_reg_296, "k_reg_296");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_413, "ap_sig_413");
    sc_trace(mVcdFile, phi_mul_reg_307, "phi_mul_reg_307");
    sc_trace(mVcdFile, i1_reg_318, "i1_reg_318");
    sc_trace(mVcdFile, exitcond6_fu_685_p2, "exitcond6_fu_685_p2");
    sc_trace(mVcdFile, phi_mul2_reg_329, "phi_mul2_reg_329");
    sc_trace(mVcdFile, j2_reg_341, "j2_reg_341");
    sc_trace(mVcdFile, exitcond7_fu_663_p2, "exitcond7_fu_663_p2");
    sc_trace(mVcdFile, phi_mul8_reg_352, "phi_mul8_reg_352");
    sc_trace(mVcdFile, k3_reg_364, "k3_reg_364");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_445, "ap_sig_445");
    sc_trace(mVcdFile, phi_mul9_reg_375, "phi_mul9_reg_375");
    sc_trace(mVcdFile, phi_mul10_reg_386, "phi_mul10_reg_386");
    sc_trace(mVcdFile, group_zero_s_reg_397, "group_zero_s_reg_397");
    sc_trace(mVcdFile, group_one_s_reg_409, "group_one_s_reg_409");
    sc_trace(mVcdFile, i4_reg_421, "i4_reg_421");
    sc_trace(mVcdFile, phi_mul4_reg_432, "phi_mul4_reg_432");
    sc_trace(mVcdFile, phi_mul6_reg_444, "phi_mul6_reg_444");
    sc_trace(mVcdFile, j5_reg_456, "j5_reg_456");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st36_fsm_35, "ap_sig_cseq_ST_st36_fsm_35");
    sc_trace(mVcdFile, ap_sig_471, "ap_sig_471");
    sc_trace(mVcdFile, phi_mul11_reg_467, "phi_mul11_reg_467");
    sc_trace(mVcdFile, k6_reg_478, "k6_reg_478");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st33_fsm_32, "ap_sig_cseq_ST_st33_fsm_32");
    sc_trace(mVcdFile, ap_sig_482, "ap_sig_482");
    sc_trace(mVcdFile, phi_mul12_reg_489, "phi_mul12_reg_489");
    sc_trace(mVcdFile, tmp_63_cast_fu_551_p1, "tmp_63_cast_fu_551_p1");
    sc_trace(mVcdFile, tmp_47_fu_625_p1, "tmp_47_fu_625_p1");
    sc_trace(mVcdFile, tmp_68_cast_fu_649_p1, "tmp_68_cast_fu_649_p1");
    sc_trace(mVcdFile, tmp_71_cast_fu_724_p1, "tmp_71_cast_fu_724_p1");
    sc_trace(mVcdFile, tmp_72_cast_fu_744_p1, "tmp_72_cast_fu_744_p1");
    sc_trace(mVcdFile, tmp_44_fu_772_p1, "tmp_44_fu_772_p1");
    sc_trace(mVcdFile, tmp_70_cast_fu_823_p1, "tmp_70_cast_fu_823_p1");
    sc_trace(mVcdFile, tmp_51_fu_812_p1, "tmp_51_fu_812_p1");
    sc_trace(mVcdFile, tmp_73_cast_fu_850_p1, "tmp_73_cast_fu_850_p1");
    sc_trace(mVcdFile, tmp_74_cast_fu_870_p1, "tmp_74_cast_fu_870_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st27_fsm_26, "ap_sig_cseq_ST_st27_fsm_26");
    sc_trace(mVcdFile, ap_sig_529, "ap_sig_529");
    sc_trace(mVcdFile, grp_fu_504_p0, "grp_fu_504_p0");
    sc_trace(mVcdFile, grp_fu_507_p0, "grp_fu_507_p0");
    sc_trace(mVcdFile, tmp_5_fu_510_p0, "tmp_5_fu_510_p0");
    sc_trace(mVcdFile, tmp_s_fu_545_p2, "tmp_s_fu_545_p2");
    sc_trace(mVcdFile, tmp_fu_578_p4, "tmp_fu_578_p4");
    sc_trace(mVcdFile, k_cast1_fu_593_p1, "k_cast1_fu_593_p1");
    sc_trace(mVcdFile, tmp1_fu_609_p2, "tmp1_fu_609_p2");
    sc_trace(mVcdFile, tmp1_cast_fu_615_p1, "tmp1_cast_fu_615_p1");
    sc_trace(mVcdFile, tmp_46_fu_619_p2, "tmp_46_fu_619_p2");
    sc_trace(mVcdFile, tmp_52_cast_fu_635_p1, "tmp_52_cast_fu_635_p1");
    sc_trace(mVcdFile, tmp_54_cast_fu_714_p1, "tmp_54_cast_fu_714_p1");
    sc_trace(mVcdFile, tmp_52_fu_718_p2, "tmp_52_fu_718_p2");
    sc_trace(mVcdFile, tmp_56_cast_fu_734_p1, "tmp_56_cast_fu_734_p1");
    sc_trace(mVcdFile, slt_fu_778_p2, "slt_fu_778_p2");
    sc_trace(mVcdFile, tmp_56_fu_817_p2, "tmp_56_fu_817_p2");
    sc_trace(mVcdFile, tmp_58_cast_fu_840_p1, "tmp_58_cast_fu_840_p1");
    sc_trace(mVcdFile, tmp_58_fu_844_p2, "tmp_58_fu_844_p2");
    sc_trace(mVcdFile, tmp_60_cast_fu_860_p1, "tmp_60_cast_fu_860_p1");
    sc_trace(mVcdFile, tmp_59_fu_864_p2, "tmp_59_fu_864_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_875_p1, "p_Val2_s_fu_875_p1");
    sc_trace(mVcdFile, tmp_49_fu_878_p1, "tmp_49_fu_878_p1");
    sc_trace(mVcdFile, p_Result_s_fu_886_p3, "p_Result_s_fu_886_p3");
    sc_trace(mVcdFile, tmp_3_fu_899_p4, "tmp_3_fu_899_p4");
    sc_trace(mVcdFile, tmp_60_fu_882_p1, "tmp_60_fu_882_p1");
    sc_trace(mVcdFile, notrhs_fu_915_p2, "notrhs_fu_915_p2");
    sc_trace(mVcdFile, notlhs_fu_909_p2, "notlhs_fu_909_p2");
    sc_trace(mVcdFile, tmp_4_fu_921_p2, "tmp_4_fu_921_p2");
    sc_trace(mVcdFile, tmp_5_fu_510_p2, "tmp_5_fu_510_p2");
    sc_trace(mVcdFile, p_Val2_25_fu_946_p1, "p_Val2_25_fu_946_p1");
    sc_trace(mVcdFile, loc_V_2_fu_968_p1, "loc_V_2_fu_968_p1");
    sc_trace(mVcdFile, p_Result_21_fu_972_p3, "p_Result_21_fu_972_p3");
    sc_trace(mVcdFile, loc_V_fu_958_p4, "loc_V_fu_958_p4");
    sc_trace(mVcdFile, tmp_i_i_i_cast2_fu_984_p1, "tmp_i_i_i_cast2_fu_984_p1");
    sc_trace(mVcdFile, sh_assign_fu_988_p2, "sh_assign_fu_988_p2");
    sc_trace(mVcdFile, tmp_117_i_i_fu_1002_p2, "tmp_117_i_i_fu_1002_p2");
    sc_trace(mVcdFile, isNeg_fu_994_p3, "isNeg_fu_994_p3");
    sc_trace(mVcdFile, tmp_117_i_i_cast_fu_1008_p1, "tmp_117_i_i_cast_fu_1008_p1");
    sc_trace(mVcdFile, sh_assign_1_fu_1012_p3, "sh_assign_1_fu_1012_p3");
    sc_trace(mVcdFile, sh_assign_1_cast_fu_1020_p1, "sh_assign_1_cast_fu_1020_p1");
    sc_trace(mVcdFile, sh_assign_1_cast_cast_fu_1024_p1, "sh_assign_1_cast_cast_fu_1024_p1");
    sc_trace(mVcdFile, tmp_i_i_fu_980_p1, "tmp_i_i_fu_980_p1");
    sc_trace(mVcdFile, tmp_118_i_i_fu_1028_p1, "tmp_118_i_i_fu_1028_p1");
    sc_trace(mVcdFile, tmp_119_i_i_fu_1032_p2, "tmp_119_i_i_fu_1032_p2");
    sc_trace(mVcdFile, tmp_65_fu_1044_p3, "tmp_65_fu_1044_p3");
    sc_trace(mVcdFile, tmp_121_i_i_fu_1038_p2, "tmp_121_i_i_fu_1038_p2");
    sc_trace(mVcdFile, tmp_62_fu_1052_p1, "tmp_62_fu_1052_p1");
    sc_trace(mVcdFile, tmp_63_fu_1056_p4, "tmp_63_fu_1056_p4");
    sc_trace(mVcdFile, p_Val2_i_i_fu_1074_p2, "p_Val2_i_i_fu_1074_p2");
    sc_trace(mVcdFile, tmp_50_fu_1086_p2, "tmp_50_fu_1086_p2");
    sc_trace(mVcdFile, group_zero_fu_1092_p2, "group_zero_fu_1092_p2");
    sc_trace(mVcdFile, group_one_fu_1098_p2, "group_one_fu_1098_p2");
    sc_trace(mVcdFile, rev_fu_784_p2, "rev_fu_784_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dut_knn::~dut_knn() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete training_data_V_U;
    delete training_data2_U;
    delete training_instance_U;
    delete min_distance_U;
    delete distance_U;
    delete group_U;
    delete dut_fsub_32ns_32ns_32_5_full_dsp_U13;
    delete dut_uitofp_32ns_32_6_U14;
    delete dut_sitofp_32ns_32_6_U15;
    delete dut_fcmp_32ns_32ns_1_1_U16;
}

void dut_knn::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dut_knn::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_3E4CCCCD;
}

void dut_knn::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_4;
}

void dut_knn::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read()))) {
            ap_return_preg = rev_fu_784_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_685_p2.read()))) {
        i1_reg_318 = i_5_reg_1227.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond10_fu_533_p2.read(), ap_const_lv1_0))) {
        i1_reg_318 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_663_p2.read()))) {
        i4_reg_421 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        i4_reg_421 = i_7_reg_1291.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_597_p2.read()))) {
        i_reg_273 = i_6_reg_1161.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond10_fu_533_p2.read(), ap_const_lv1_0))) {
        i_reg_273 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_697_p2.read()))) {
        j2_reg_341 = j_7_reg_1245.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_663_p2.read()))) {
        j2_reg_341 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read()))) {
        j5_reg_456 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read())) {
        j5_reg_456 = j_8_reg_1319.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        j_reg_226 = j_6_reg_1138.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        j_reg_226 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_685_p2.read()))) {
        k3_reg_364 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        k3_reg_364 = k_3_reg_1253.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_800_p2.read()))) {
        k6_reg_478 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st33_fsm_32.read())) {
        k6_reg_478 = k_4_reg_1337.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_566_p2.read()))) {
        k_reg_296 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        k_reg_296 = k_2_reg_1174.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_685_p2.read()))) {
        phi_mul10_reg_386 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        phi_mul10_reg_386 = next_mul12_reg_1268.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read()))) {
        phi_mul11_reg_467 = ap_const_lv14_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read())) {
        phi_mul11_reg_467 = next_mul11_reg_1306.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_800_p2.read()))) {
        phi_mul12_reg_489 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st33_fsm_32.read())) {
        phi_mul12_reg_489 = next_mul13_reg_1347.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_597_p2.read()))) {
        phi_mul1_reg_284 = next_mul2_reg_1148.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond10_fu_533_p2.read(), ap_const_lv1_0))) {
        phi_mul1_reg_284 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_685_p2.read()))) {
        phi_mul2_reg_329 = next_mul3_reg_1214.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond10_fu_533_p2.read(), ap_const_lv1_0))) {
        phi_mul2_reg_329 = ap_const_lv14_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        phi_mul3_reg_237 = next_mul4_reg_1130.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        phi_mul3_reg_237 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_663_p2.read()))) {
        phi_mul4_reg_432 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        phi_mul4_reg_432 = next_mul7_reg_1283.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        phi_mul5_reg_249 = next_mul6_reg_1125.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        phi_mul5_reg_249 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_663_p2.read()))) {
        phi_mul6_reg_444 = ap_const_lv14_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        phi_mul6_reg_444 = next_mul5_reg_1278.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        phi_mul7_reg_261 = next_mul8_reg_1120.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        phi_mul7_reg_261 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_697_p2.read()))) {
        phi_mul8_reg_352 = next_mul9_reg_1232.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_663_p2.read()))) {
        phi_mul8_reg_352 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_685_p2.read()))) {
        phi_mul9_reg_375 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        phi_mul9_reg_375 = next_mul10_reg_1258.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_566_p2.read()))) {
        phi_mul_reg_307 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        phi_mul_reg_307 = next_mul_reg_1184.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_800_p2.read()))) {
        distance_addr_reg_1329 =  (sc_lv<4>) (tmp_51_fu_812_p1.read());
        training_data2_addr_3_reg_1324 =  (sc_lv<14>) (tmp_70_cast_fu_823_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read()))) {
        group_addr_reg_1301 =  (sc_lv<5>) (tmp_44_fu_772_p1.read());
        min_distance_addr_reg_1296 =  (sc_lv<5>) (tmp_44_fu_772_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        group_one_s_reg_409 = group_one_1_fu_1112_p3.read();
        group_zero_s_reg_397 = group_zero_1_fu_1104_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        i1_cast_cast_reg_1219 = i1_cast_cast_fu_659_p1.read();
        i_5_reg_1227 = i_5_fu_669_p2.read();
        next_mul3_reg_1214 = next_mul3_fu_653_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_6_reg_1161 = i_6_fu_572_p2.read();
        i_cast_cast_reg_1153 = i_cast_cast_fu_562_p1.read();
        next_mul2_reg_1148 = next_mul2_fu_556_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        i_7_reg_1291 = i_7_fu_766_p2.read();
        next_mul5_reg_1278 = next_mul5_fu_748_p2.read();
        next_mul7_reg_1283 = next_mul7_fu_754_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read())) {
        input_load_reg_1357 = input_r_q0.read();
        training_instance_load_reg_1362 = training_instance_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        j2_cast_reg_1237 = j2_cast_fu_681_p1.read();
        j_7_reg_1245 = j_7_fu_691_p2.read();
        next_mul9_reg_1232 = next_mul9_fu_675_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        j5_cast6_reg_1311 = j5_cast6_fu_796_p1.read();
        j_8_reg_1319 = j_8_fu_806_p2.read();
        next_mul11_reg_1306 = next_mul11_fu_790_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        j_6_reg_1138 = j_6_fu_539_p2.read();
        next_mul4_reg_1130 = next_mul4_fu_527_p2.read();
        next_mul6_reg_1125 = next_mul6_fu_521_p2.read();
        next_mul8_reg_1120 = next_mul8_fu_515_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        k_2_reg_1174 = k_2_fu_603_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        k_3_reg_1253 = k_3_fu_703_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        k_4_reg_1337 = k_4_fu_834_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_697_p2.read()))) {
        next_mul10_reg_1258 = next_mul10_fu_709_p2.read();
        next_mul12_reg_1268 = next_mul12_fu_729_p2.read();
        tmp_53_reg_1273 = tmp_53_fu_738_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_828_p2.read()))) {
        next_mul13_reg_1347 = next_mul13_fu_855_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_597_p2.read()))) {
        next_mul_reg_1184 = next_mul_fu_630_p2.read();
        tmp_55_reg_1189 = tmp_55_fu_639_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st35_fsm_34.read())) {
        p_Result_20_reg_1380 = p_Val2_25_fu_946_p1.read().range(31, 31);
        p_Val2_28_reg_1385 = p_Val2_28_fu_1066_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        p_x_assign_reg_1367 = grp_fu_500_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        tmp_42_reg_1209 = grp_fu_507_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        tmp_48_reg_1204 = grp_fu_504_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read())) {
        tmp_57_reg_1376 = tmp_57_fu_940_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read())) {
        tmp_6_reg_1372 = tmp_6_fu_927_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond10_fu_533_p2.read(), ap_const_lv1_0))) {
        training_data2_addr_reg_1143 =  (sc_lv<14>) (tmp_63_cast_fu_551_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        training_data_V_load_reg_1194 = training_data_V_q0.read();
    }
}

void dut_knn::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read()))) {
        ap_return = rev_fu_784_p2.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void dut_knn::thread_ap_sig_101() {
    ap_sig_101 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_knn::thread_ap_sig_120() {
    ap_sig_120 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_knn::thread_ap_sig_137() {
    ap_sig_137 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_knn::thread_ap_sig_146() {
    ap_sig_146 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_knn::thread_ap_sig_155() {
    ap_sig_155 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dut_knn::thread_ap_sig_164() {
    ap_sig_164 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void dut_knn::thread_ap_sig_173() {
    ap_sig_173 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void dut_knn::thread_ap_sig_186() {
    ap_sig_186 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void dut_knn::thread_ap_sig_199() {
    ap_sig_199 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void dut_knn::thread_ap_sig_219() {
    ap_sig_219 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void dut_knn::thread_ap_sig_239() {
    ap_sig_239 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void dut_knn::thread_ap_sig_259() {
    ap_sig_259 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(24, 24));
}

void dut_knn::thread_ap_sig_276() {
    ap_sig_276 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(25, 25));
}

void dut_knn::thread_ap_sig_287() {
    ap_sig_287 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(30, 30));
}

void dut_knn::thread_ap_sig_296() {
    ap_sig_296 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(31, 31));
}

void dut_knn::thread_ap_sig_305() {
    ap_sig_305 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(33, 33));
}

void dut_knn::thread_ap_sig_314() {
    ap_sig_314 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(34, 34));
}

void dut_knn::thread_ap_sig_325() {
    ap_sig_325 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(36, 36));
}

void dut_knn::thread_ap_sig_388() {
    ap_sig_388 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void dut_knn::thread_ap_sig_413() {
    ap_sig_413 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dut_knn::thread_ap_sig_445() {
    ap_sig_445 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void dut_knn::thread_ap_sig_471() {
    ap_sig_471 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(35, 35));
}

void dut_knn::thread_ap_sig_482() {
    ap_sig_482 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(32, 32));
}

void dut_knn::thread_ap_sig_529() {
    ap_sig_529 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(26, 26));
}

void dut_knn::thread_ap_sig_54() {
    ap_sig_54 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_knn::thread_ap_sig_80() {
    ap_sig_80 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_knn::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_155.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_413.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_164.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_388.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_173.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_54.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_186.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_199.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_445.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_219.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_239.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st25_fsm_24() {
    if (ap_sig_259.read()) {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st26_fsm_25() {
    if (ap_sig_276.read()) {
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st27_fsm_26() {
    if (ap_sig_529.read()) {
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_80.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st31_fsm_30() {
    if (ap_sig_287.read()) {
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st32_fsm_31() {
    if (ap_sig_296.read()) {
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st33_fsm_32() {
    if (ap_sig_482.read()) {
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st34_fsm_33() {
    if (ap_sig_305.read()) {
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st35_fsm_34() {
    if (ap_sig_314.read()) {
        ap_sig_cseq_ST_st35_fsm_34 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st35_fsm_34 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st36_fsm_35() {
    if (ap_sig_471.read()) {
        ap_sig_cseq_ST_st36_fsm_35 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st36_fsm_35 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st37_fsm_36() {
    if (ap_sig_325.read()) {
        ap_sig_cseq_ST_st37_fsm_36 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st37_fsm_36 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_101.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_120.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_137.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_146.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_knn::thread_distance_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st33_fsm_32.read()))) {
        distance_ce0 = ap_const_logic_1;
    } else {
        distance_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_distance_d0() {
    distance_d0 = (!distance_q0.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(distance_q0.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void dut_knn::thread_distance_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st33_fsm_32.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_reg_1372.read())))) {
        distance_we0 = ap_const_logic_1;
    } else {
        distance_we0 = ap_const_logic_0;
    }
}

void dut_knn::thread_exitcond10_fu_533_p2() {
    exitcond10_fu_533_p2 = (!j_reg_226.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_226.read() == ap_const_lv4_E);
}

void dut_knn::thread_exitcond3_fu_800_p2() {
    exitcond3_fu_800_p2 = (!j5_reg_456.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j5_reg_456.read() == ap_const_lv4_E);
}

void dut_knn::thread_exitcond4_fu_760_p2() {
    exitcond4_fu_760_p2 = (!i4_reg_421.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i4_reg_421.read() == ap_const_lv5_14);
}

void dut_knn::thread_exitcond5_fu_697_p2() {
    exitcond5_fu_697_p2 = (!k3_reg_364.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(k3_reg_364.read() == ap_const_lv6_31);
}

void dut_knn::thread_exitcond6_fu_685_p2() {
    exitcond6_fu_685_p2 = (!j2_reg_341.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j2_reg_341.read() == ap_const_lv4_E);
}

void dut_knn::thread_exitcond7_fu_663_p2() {
    exitcond7_fu_663_p2 = (!i1_reg_318.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_318.read() == ap_const_lv5_14);
}

void dut_knn::thread_exitcond8_fu_597_p2() {
    exitcond8_fu_597_p2 = (!k_reg_296.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_296.read() == ap_const_lv6_31);
}

void dut_knn::thread_exitcond9_fu_566_p2() {
    exitcond9_fu_566_p2 = (!i_reg_273.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_273.read() == ap_const_lv5_14);
}

void dut_knn::thread_exitcond_fu_828_p2() {
    exitcond_fu_828_p2 = (!k6_reg_478.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(k6_reg_478.read() == ap_const_lv6_31);
}

void dut_knn::thread_group_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read()))) {
        group_ce0 = ap_const_logic_1;
    } else {
        group_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_group_d0() {
    group_d0 = (!p_Result_20_reg_1380.read()[0].is_01())? sc_lv<32>(): ((p_Result_20_reg_1380.read()[0].to_bool())? p_Val2_i_i_fu_1074_p2.read(): p_Val2_28_reg_1385.read());
}

void dut_knn::thread_group_one_1_fu_1112_p3() {
    group_one_1_fu_1112_p3 = (!tmp_50_fu_1086_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_50_fu_1086_p2.read()[0].to_bool())? group_one_s_reg_409.read(): group_one_fu_1098_p2.read());
}

void dut_knn::thread_group_one_fu_1098_p2() {
    group_one_fu_1098_p2 = (!group_one_s_reg_409.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(group_one_s_reg_409.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void dut_knn::thread_group_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_57_reg_1376.read())))) {
        group_we0 = ap_const_logic_1;
    } else {
        group_we0 = ap_const_logic_0;
    }
}

void dut_knn::thread_group_zero_1_fu_1104_p3() {
    group_zero_1_fu_1104_p3 = (!tmp_50_fu_1086_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_50_fu_1086_p2.read()[0].to_bool())? group_zero_fu_1092_p2.read(): group_zero_s_reg_397.read());
}

void dut_knn::thread_group_zero_fu_1092_p2() {
    group_zero_fu_1092_p2 = (!group_zero_s_reg_397.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(group_zero_s_reg_397.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void dut_knn::thread_grp_fu_504_p0() {
    grp_fu_504_p0 = esl_zext<32,6>(training_data_V_load_reg_1194.read());
}

void dut_knn::thread_grp_fu_507_p0() {
    grp_fu_507_p0 = esl_zext<32,2>(tmp_fu_578_p4.read());
}

void dut_knn::thread_i1_cast_cast_fu_659_p1() {
    i1_cast_cast_fu_659_p1 = esl_zext<10,5>(i1_reg_318.read());
}

void dut_knn::thread_i_5_fu_669_p2() {
    i_5_fu_669_p2 = (!i1_reg_318.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i1_reg_318.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_knn::thread_i_6_fu_572_p2() {
    i_6_fu_572_p2 = (!i_reg_273.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_273.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_knn::thread_i_7_fu_766_p2() {
    i_7_fu_766_p2 = (!i4_reg_421.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i4_reg_421.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_knn::thread_i_cast_cast_fu_562_p1() {
    i_cast_cast_fu_562_p1 = esl_zext<10,5>(i_reg_273.read());
}

void dut_knn::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<10>) (tmp_73_cast_fu_850_p1.read());
}

void dut_knn::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_isNeg_fu_994_p3() {
    isNeg_fu_994_p3 = sh_assign_fu_988_p2.read().range(8, 8);
}

void dut_knn::thread_j2_cast_fu_681_p1() {
    j2_cast_fu_681_p1 = esl_zext<10,4>(j2_reg_341.read());
}

void dut_knn::thread_j5_cast6_fu_796_p1() {
    j5_cast6_fu_796_p1 = esl_zext<10,4>(j5_reg_456.read());
}

void dut_knn::thread_j_6_fu_539_p2() {
    j_6_fu_539_p2 = (!j_reg_226.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_226.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn::thread_j_7_fu_691_p2() {
    j_7_fu_691_p2 = (!j2_reg_341.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j2_reg_341.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn::thread_j_8_fu_806_p2() {
    j_8_fu_806_p2 = (!j5_reg_456.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j5_reg_456.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn::thread_k_2_fu_603_p2() {
    k_2_fu_603_p2 = (!k_reg_296.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(k_reg_296.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut_knn::thread_k_3_fu_703_p2() {
    k_3_fu_703_p2 = (!k3_reg_364.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(k3_reg_364.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut_knn::thread_k_4_fu_834_p2() {
    k_4_fu_834_p2 = (!k6_reg_478.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(k6_reg_478.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut_knn::thread_k_cast1_fu_593_p1() {
    k_cast1_fu_593_p1 = esl_zext<10,6>(k_reg_296.read());
}

void dut_knn::thread_loc_V_2_fu_968_p1() {
    loc_V_2_fu_968_p1 = p_Val2_25_fu_946_p1.read().range(23-1, 0);
}

void dut_knn::thread_loc_V_fu_958_p4() {
    loc_V_fu_958_p4 = p_Val2_25_fu_946_p1.read().range(30, 23);
}

void dut_knn::thread_min_distance_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read()))) {
        min_distance_ce0 = ap_const_logic_1;
    } else {
        min_distance_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_min_distance_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_57_fu_940_p2.read())))) {
        min_distance_we0 = ap_const_logic_1;
    } else {
        min_distance_we0 = ap_const_logic_0;
    }
}

void dut_knn::thread_next_mul10_fu_709_p2() {
    next_mul10_fu_709_p2 = (!i1_cast_cast_reg_1219.read().is_01() || !phi_mul9_reg_375.read().is_01())? sc_lv<10>(): (sc_biguint<10>(i1_cast_cast_reg_1219.read()) + sc_biguint<10>(phi_mul9_reg_375.read()));
}

void dut_knn::thread_next_mul11_fu_790_p2() {
    next_mul11_fu_790_p2 = (!phi_mul11_reg_467.read().is_01() || !ap_const_lv14_3D5.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul11_reg_467.read()) + sc_biguint<14>(ap_const_lv14_3D5));
}

void dut_knn::thread_next_mul12_fu_729_p2() {
    next_mul12_fu_729_p2 = (!j2_cast_reg_1237.read().is_01() || !phi_mul10_reg_386.read().is_01())? sc_lv<10>(): (sc_biguint<10>(j2_cast_reg_1237.read()) + sc_biguint<10>(phi_mul10_reg_386.read()));
}

void dut_knn::thread_next_mul13_fu_855_p2() {
    next_mul13_fu_855_p2 = (!phi_mul12_reg_489.read().is_01() || !j5_cast6_reg_1311.read().is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul12_reg_489.read()) + sc_biguint<10>(j5_cast6_reg_1311.read()));
}

void dut_knn::thread_next_mul2_fu_556_p2() {
    next_mul2_fu_556_p2 = (!phi_mul1_reg_284.read().is_01() || !ap_const_lv10_32.is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul1_reg_284.read()) + sc_biguint<10>(ap_const_lv10_32));
}

void dut_knn::thread_next_mul3_fu_653_p2() {
    next_mul3_fu_653_p2 = (!phi_mul2_reg_329.read().is_01() || !ap_const_lv14_2AE.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul2_reg_329.read()) + sc_biguint<14>(ap_const_lv14_2AE));
}

void dut_knn::thread_next_mul4_fu_527_p2() {
    next_mul4_fu_527_p2 = (!phi_mul3_reg_237.read().is_01() || !ap_const_lv9_13.is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul3_reg_237.read()) + sc_biguint<9>(ap_const_lv9_13));
}

void dut_knn::thread_next_mul5_fu_748_p2() {
    next_mul5_fu_748_p2 = (!phi_mul6_reg_444.read().is_01() || !ap_const_lv14_2AE.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul6_reg_444.read()) + sc_biguint<14>(ap_const_lv14_2AE));
}

void dut_knn::thread_next_mul6_fu_521_p2() {
    next_mul6_fu_521_p2 = (!phi_mul5_reg_249.read().is_01() || !ap_const_lv14_3E8.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul5_reg_249.read()) + sc_biguint<14>(ap_const_lv14_3E8));
}

void dut_knn::thread_next_mul7_fu_754_p2() {
    next_mul7_fu_754_p2 = (!phi_mul4_reg_432.read().is_01() || !ap_const_lv10_31.is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul4_reg_432.read()) + sc_biguint<10>(ap_const_lv10_31));
}

void dut_knn::thread_next_mul8_fu_515_p2() {
    next_mul8_fu_515_p2 = (!phi_mul7_reg_261.read().is_01() || !ap_const_lv14_3D5.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul7_reg_261.read()) + sc_biguint<14>(ap_const_lv14_3D5));
}

void dut_knn::thread_next_mul9_fu_675_p2() {
    next_mul9_fu_675_p2 = (!phi_mul8_reg_352.read().is_01() || !ap_const_lv14_3D5.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul8_reg_352.read()) + sc_biguint<14>(ap_const_lv14_3D5));
}

void dut_knn::thread_next_mul_fu_630_p2() {
    next_mul_fu_630_p2 = (!i_cast_cast_reg_1153.read().is_01() || !phi_mul_reg_307.read().is_01())? sc_lv<10>(): (sc_biguint<10>(i_cast_cast_reg_1153.read()) + sc_biguint<10>(phi_mul_reg_307.read()));
}

void dut_knn::thread_notlhs_fu_909_p2() {
    notlhs_fu_909_p2 = (!tmp_3_fu_899_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_3_fu_899_p4.read() != ap_const_lv8_FF);
}

void dut_knn::thread_notrhs_fu_915_p2() {
    notrhs_fu_915_p2 = (!tmp_60_fu_882_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_60_fu_882_p1.read() == ap_const_lv23_0);
}

void dut_knn::thread_p_Result_21_fu_972_p3() {
    p_Result_21_fu_972_p3 = esl_concat<1,23>(ap_const_lv1_1, loc_V_2_fu_968_p1.read());
}

void dut_knn::thread_p_Result_s_fu_886_p3() {
    p_Result_s_fu_886_p3 = esl_concat<1,31>(ap_const_lv1_0, tmp_49_fu_878_p1.read());
}

void dut_knn::thread_p_Val2_25_fu_946_p1() {
    p_Val2_25_fu_946_p1 = training_data2_q0.read();
}

void dut_knn::thread_p_Val2_28_fu_1066_p3() {
    p_Val2_28_fu_1066_p3 = (!isNeg_fu_994_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_994_p3.read()[0].to_bool())? tmp_62_fu_1052_p1.read(): tmp_63_fu_1056_p4.read());
}

void dut_knn::thread_p_Val2_i_i_fu_1074_p2() {
    p_Val2_i_i_fu_1074_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_28_reg_1385.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_28_reg_1385.read()));
}

void dut_knn::thread_p_Val2_s_fu_875_p1() {
    p_Val2_s_fu_875_p1 = p_x_assign_reg_1367.read();
}

void dut_knn::thread_rev_fu_784_p2() {
    rev_fu_784_p2 = (slt_fu_778_p2.read() ^ ap_const_lv1_1);
}

void dut_knn::thread_sh_assign_1_cast_cast_fu_1024_p1() {
    sh_assign_1_cast_cast_fu_1024_p1 = esl_sext<24,9>(sh_assign_1_fu_1012_p3.read());
}

void dut_knn::thread_sh_assign_1_cast_fu_1020_p1() {
    sh_assign_1_cast_fu_1020_p1 = esl_sext<32,9>(sh_assign_1_fu_1012_p3.read());
}

void dut_knn::thread_sh_assign_1_fu_1012_p3() {
    sh_assign_1_fu_1012_p3 = (!isNeg_fu_994_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_994_p3.read()[0].to_bool())? tmp_117_i_i_cast_fu_1008_p1.read(): sh_assign_fu_988_p2.read());
}

void dut_knn::thread_sh_assign_fu_988_p2() {
    sh_assign_fu_988_p2 = (!ap_const_lv9_181.is_01() || !tmp_i_i_i_cast2_fu_984_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(tmp_i_i_i_cast2_fu_984_p1.read()));
}

void dut_knn::thread_slt_fu_778_p2() {
    slt_fu_778_p2 = (!group_one_s_reg_409.read().is_01() || !group_zero_s_reg_397.read().is_01())? sc_lv<1>(): (sc_bigint<32>(group_one_s_reg_409.read()) < sc_bigint<32>(group_zero_s_reg_397.read()));
}

void dut_knn::thread_tmp1_cast_fu_615_p1() {
    tmp1_cast_fu_615_p1 = esl_zext<14,10>(tmp1_fu_609_p2.read());
}

void dut_knn::thread_tmp1_fu_609_p2() {
    tmp1_fu_609_p2 = (!k_cast1_fu_593_p1.read().is_01() || !phi_mul1_reg_284.read().is_01())? sc_lv<10>(): (sc_biguint<10>(k_cast1_fu_593_p1.read()) + sc_biguint<10>(phi_mul1_reg_284.read()));
}

void dut_knn::thread_tmp_117_i_i_cast_fu_1008_p1() {
    tmp_117_i_i_cast_fu_1008_p1 = esl_sext<9,8>(tmp_117_i_i_fu_1002_p2.read());
}

void dut_knn::thread_tmp_117_i_i_fu_1002_p2() {
    tmp_117_i_i_fu_1002_p2 = (!ap_const_lv8_7F.is_01() || !loc_V_fu_958_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(loc_V_fu_958_p4.read()));
}

void dut_knn::thread_tmp_118_i_i_fu_1028_p1() {
    tmp_118_i_i_fu_1028_p1 = esl_zext<78,32>(sh_assign_1_cast_fu_1020_p1.read());
}

void dut_knn::thread_tmp_119_i_i_fu_1032_p2() {
    tmp_119_i_i_fu_1032_p2 = (!sh_assign_1_cast_cast_fu_1024_p1.read().is_01())? sc_lv<24>(): p_Result_21_fu_972_p3.read() >> (unsigned short)sh_assign_1_cast_cast_fu_1024_p1.read().to_uint();
}

void dut_knn::thread_tmp_121_i_i_fu_1038_p2() {
    tmp_121_i_i_fu_1038_p2 = (!tmp_118_i_i_fu_1028_p1.read().is_01())? sc_lv<78>(): tmp_i_i_fu_980_p1.read() << (unsigned short)tmp_118_i_i_fu_1028_p1.read().to_uint();
}

void dut_knn::thread_tmp_3_fu_899_p4() {
    tmp_3_fu_899_p4 = p_Val2_s_fu_875_p1.read().range(30, 23);
}

void dut_knn::thread_tmp_44_fu_772_p1() {
    tmp_44_fu_772_p1 = esl_zext<64,5>(i4_reg_421.read());
}

void dut_knn::thread_tmp_46_fu_619_p2() {
    tmp_46_fu_619_p2 = (!phi_mul5_reg_249.read().is_01() || !tmp1_cast_fu_615_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul5_reg_249.read()) + sc_biguint<14>(tmp1_cast_fu_615_p1.read()));
}

void dut_knn::thread_tmp_47_fu_625_p1() {
    tmp_47_fu_625_p1 = esl_zext<64,14>(tmp_46_fu_619_p2.read());
}

void dut_knn::thread_tmp_49_fu_878_p1() {
    tmp_49_fu_878_p1 = p_Val2_s_fu_875_p1.read().range(31-1, 0);
}

void dut_knn::thread_tmp_4_fu_921_p2() {
    tmp_4_fu_921_p2 = (notrhs_fu_915_p2.read() | notlhs_fu_909_p2.read());
}

void dut_knn::thread_tmp_50_fu_1086_p2() {
    tmp_50_fu_1086_p2 = (!group_q0.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(group_q0.read() == ap_const_lv32_0);
}

void dut_knn::thread_tmp_51_fu_812_p1() {
    tmp_51_fu_812_p1 = esl_zext<64,4>(j5_reg_456.read());
}

void dut_knn::thread_tmp_52_cast_fu_635_p1() {
    tmp_52_cast_fu_635_p1 = esl_zext<14,10>(phi_mul_reg_307.read());
}

void dut_knn::thread_tmp_52_fu_718_p2() {
    tmp_52_fu_718_p2 = (!phi_mul8_reg_352.read().is_01() || !tmp_54_cast_fu_714_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul8_reg_352.read()) + sc_biguint<14>(tmp_54_cast_fu_714_p1.read()));
}

void dut_knn::thread_tmp_53_fu_738_p2() {
    tmp_53_fu_738_p2 = (!phi_mul2_reg_329.read().is_01() || !tmp_56_cast_fu_734_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul2_reg_329.read()) + sc_biguint<14>(tmp_56_cast_fu_734_p1.read()));
}

void dut_knn::thread_tmp_54_cast_fu_714_p1() {
    tmp_54_cast_fu_714_p1 = esl_zext<14,10>(phi_mul9_reg_375.read());
}

void dut_knn::thread_tmp_55_fu_639_p2() {
    tmp_55_fu_639_p2 = (!phi_mul7_reg_261.read().is_01() || !tmp_52_cast_fu_635_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul7_reg_261.read()) + sc_biguint<14>(tmp_52_cast_fu_635_p1.read()));
}

void dut_knn::thread_tmp_56_cast_fu_734_p1() {
    tmp_56_cast_fu_734_p1 = esl_zext<14,10>(phi_mul10_reg_386.read());
}

void dut_knn::thread_tmp_56_fu_817_p2() {
    tmp_56_fu_817_p2 = (!phi_mul11_reg_467.read().is_01() || !ap_const_lv14_3D4.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul11_reg_467.read()) + sc_biguint<14>(ap_const_lv14_3D4));
}

void dut_knn::thread_tmp_57_fu_940_p2() {
    tmp_57_fu_940_p2 = (!distance_q0.read().is_01() || !min_distance_q0.read().is_01())? sc_lv<1>(): (sc_bigint<32>(distance_q0.read()) < sc_bigint<32>(min_distance_q0.read()));
}

void dut_knn::thread_tmp_58_cast_fu_840_p1() {
    tmp_58_cast_fu_840_p1 = esl_zext<10,6>(k6_reg_478.read());
}

void dut_knn::thread_tmp_58_fu_844_p2() {
    tmp_58_fu_844_p2 = (!tmp_58_cast_fu_840_p1.read().is_01() || !phi_mul4_reg_432.read().is_01())? sc_lv<10>(): (sc_biguint<10>(tmp_58_cast_fu_840_p1.read()) + sc_biguint<10>(phi_mul4_reg_432.read()));
}

void dut_knn::thread_tmp_59_fu_864_p2() {
    tmp_59_fu_864_p2 = (!tmp_60_cast_fu_860_p1.read().is_01() || !phi_mul6_reg_444.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_60_cast_fu_860_p1.read()) + sc_biguint<14>(phi_mul6_reg_444.read()));
}

void dut_knn::thread_tmp_5_fu_510_p0() {
    tmp_5_fu_510_p0 = p_Result_s_fu_886_p3.read();
}

void dut_knn::thread_tmp_60_cast_fu_860_p1() {
    tmp_60_cast_fu_860_p1 = esl_zext<14,10>(phi_mul12_reg_489.read());
}

void dut_knn::thread_tmp_60_fu_882_p1() {
    tmp_60_fu_882_p1 = p_Val2_s_fu_875_p1.read().range(23-1, 0);
}

void dut_knn::thread_tmp_62_fu_1052_p1() {
    tmp_62_fu_1052_p1 = esl_zext<32,1>(tmp_65_fu_1044_p3.read());
}

void dut_knn::thread_tmp_63_cast_fu_551_p1() {
    tmp_63_cast_fu_551_p1 = esl_zext<64,14>(tmp_s_fu_545_p2.read());
}

void dut_knn::thread_tmp_63_fu_1056_p4() {
    tmp_63_fu_1056_p4 = tmp_121_i_i_fu_1038_p2.read().range(54, 23);
}

void dut_knn::thread_tmp_65_fu_1044_p3() {
    tmp_65_fu_1044_p3 = tmp_119_i_i_fu_1032_p2.read().range(23, 23);
}

void dut_knn::thread_tmp_68_cast_fu_649_p1() {
    tmp_68_cast_fu_649_p1 = esl_zext<64,14>(tmp_55_reg_1189.read());
}

void dut_knn::thread_tmp_6_fu_927_p2() {
    tmp_6_fu_927_p2 = (tmp_4_fu_921_p2.read() & tmp_5_fu_510_p2.read());
}

void dut_knn::thread_tmp_70_cast_fu_823_p1() {
    tmp_70_cast_fu_823_p1 = esl_zext<64,14>(tmp_56_fu_817_p2.read());
}

void dut_knn::thread_tmp_71_cast_fu_724_p1() {
    tmp_71_cast_fu_724_p1 = esl_zext<64,14>(tmp_52_fu_718_p2.read());
}

void dut_knn::thread_tmp_72_cast_fu_744_p1() {
    tmp_72_cast_fu_744_p1 = esl_zext<64,14>(tmp_53_reg_1273.read());
}

void dut_knn::thread_tmp_73_cast_fu_850_p1() {
    tmp_73_cast_fu_850_p1 = esl_zext<64,10>(tmp_58_fu_844_p2.read());
}

void dut_knn::thread_tmp_74_cast_fu_870_p1() {
    tmp_74_cast_fu_870_p1 = esl_zext<64,14>(tmp_59_fu_864_p2.read());
}

void dut_knn::thread_tmp_fu_578_p4() {
    tmp_fu_578_p4 = phi_mul3_reg_237.read().range(8, 7);
}

void dut_knn::thread_tmp_i_i_fu_980_p1() {
    tmp_i_i_fu_980_p1 = esl_zext<78,24>(p_Result_21_fu_972_p3.read());
}

void dut_knn::thread_tmp_i_i_i_cast2_fu_984_p1() {
    tmp_i_i_i_cast2_fu_984_p1 = esl_zext<9,8>(loc_V_fu_958_p4.read());
}

void dut_knn::thread_tmp_s_fu_545_p2() {
    tmp_s_fu_545_p2 = (!phi_mul7_reg_261.read().is_01() || !ap_const_lv14_3D4.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul7_reg_261.read()) + sc_biguint<14>(ap_const_lv14_3D4));
}

void dut_knn::thread_training_data2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        training_data2_address0 = training_data2_addr_reg_1143.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        training_data2_address0 =  (sc_lv<14>) (tmp_68_cast_fu_649_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read())) {
        training_data2_address0 = training_data2_addr_3_reg_1324.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        training_data2_address0 =  (sc_lv<14>) (tmp_71_cast_fu_724_p1.read());
    } else {
        training_data2_address0 = "XXXXXXXXXXXXXX";
    }
}

void dut_knn::thread_training_data2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        training_data2_ce0 = ap_const_logic_1;
    } else {
        training_data2_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_training_data2_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        training_data2_d0 = tmp_42_reg_1209.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        training_data2_d0 = tmp_48_reg_1204.read();
    } else {
        training_data2_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut_knn::thread_training_data2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        training_data2_we0 = ap_const_logic_1;
    } else {
        training_data2_we0 = ap_const_logic_0;
    }
}

void dut_knn::thread_training_data_V_address0() {
    training_data_V_address0 =  (sc_lv<14>) (tmp_47_fu_625_p1.read());
}

void dut_knn::thread_training_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        training_data_V_ce0 = ap_const_logic_1;
    } else {
        training_data_V_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_training_instance_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        training_instance_address0 =  (sc_lv<14>) (tmp_72_cast_fu_744_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        training_instance_address0 =  (sc_lv<14>) (tmp_74_cast_fu_870_p1.read());
    } else {
        training_instance_address0 = "XXXXXXXXXXXXXX";
    }
}

void dut_knn::thread_training_instance_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        training_instance_ce0 = ap_const_logic_1;
    } else {
        training_instance_ce0 = ap_const_logic_0;
    }
}

void dut_knn::thread_training_instance_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        training_instance_we0 = ap_const_logic_1;
    } else {
        training_instance_we0 = ap_const_logic_0;
    }
}

void dut_knn::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond10_fu_533_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_566_p2.read())) {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_597_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 262144 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_663_p2.read())) {
                ap_NS_fsm = ap_ST_st23_fsm_22;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 524288 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_685_p2.read())) {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            } else {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            }
            break;
        case 1048576 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_697_p2.read())) {
                ap_NS_fsm = ap_ST_st22_fsm_21;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 4194304 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_760_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            }
            break;
        case 8388608 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_800_p2.read())) {
                ap_NS_fsm = ap_ST_st25_fsm_24;
            } else {
                ap_NS_fsm = ap_ST_st37_fsm_36;
            }
            break;
        case 16777216 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_828_p2.read())) {
                ap_NS_fsm = ap_ST_st34_fsm_33;
            } else {
                ap_NS_fsm = ap_ST_st26_fsm_25;
            }
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
            break;
        case 8589934592 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_57_fu_940_p2.read())) {
                ap_NS_fsm = ap_ST_st36_fsm_35;
            } else {
                ap_NS_fsm = ap_ST_st35_fsm_34;
            }
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<37>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

